import React,{useRef,useState} from 'react';
import {Plus,Swords,ChevronLeft,ChevronRight,BookMarked,Star,Pencil,Trash2,Archive,ScrollText,Copy} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Table,TableHeader,TableBody,TableHead,TableRow,TableCell} from '@/components/ui/table';
import {Check,Choice,IconButton} from './ui';
import CombatLog from './combat-log';
import {ACTION_KINDS,OUTCOMES,removeCombatant,type CombatAction} from '@/lib/combat';
import type {DMBoard,Combatant,Bestiary,Entry} from '@/lib/campaign';

type Change={id:string;effect:'none'|'damage'|'heal';amount:number;conditions:string;changeConditions:boolean};
type ActionDraft={action:CombatAction;changes:Change[];board:DMBoard;version:number};
export default function CombatTracker({board,version,onSave,bestiary,bestiaryVersion,onSaveBestiary,records,onArchive}:{board:DMBoard;version:number;onSave:(b:DMBoard,v:number,a?:CombatAction)=>Promise<void>;bestiary:Bestiary;bestiaryVersion:number;onSaveBestiary:(b:Bestiary,v:number)=>Promise<void>;records:Entry[];onArchive:(data:any)=>Promise<void>}){
 const [draft,setDraft]=useState<Combatant|null>(null);const [base,setBase]=useState({board,version});
 const [action,setAction]=useState<ActionDraft|null>(null);const [busy,setBusy]=useState(false);const lock=useRef(false);const [error,setError]=useState('');
 const [library,setLibrary]=useState(false);const [copies,setCopies]=useState(1);const [removeId,setRemoveId]=useState('');
 const [archive,setArchive]=useState(false);const [title,setTitle]=useState('');const [links,setLinks]=useState<string[]>([]);
 const sorted=[...board.combatants].sort((a,b)=>b.initiative-a.initiative||a.name.localeCompare(b.name));
 const current=sorted.find(c=>c.id===board.turnId)||sorted[0];const index=sorted.findIndex(c=>c.id===current?.id);
 async function perform(work:()=>Promise<void>){if(lock.current)return false;lock.current=true;setBusy(true);setError('');try{await work();return true;}catch(e){setError((e as Error).message);return false;}finally{lock.current=false;setBusy(false);}}
 const commit=(next:DMBoard,v=version,a?:CombatAction)=>perform(()=>onSave(next,v,a));
 function open(c?:Combatant){setBase({board,version});setError('');setDraft(c?{...c}:{id:crypto.randomUUID(),name:'',initiative:0,ac:10,hp:10,maxHp:10,conditions:'',notes:''});}
 function nextTurn(direction:number){let at=index+direction,round=board.round;if(at>=sorted.length){at=0;round++;}if(at<0){if(round===1)return;at=sorted.length-1;round--;}void commit({...board,round,turnId:sorted[at].id});}
 function record(kind:CombatAction['kind']='action',target?:Combatant){setError('');setAction({board,version,action:{kind,sourceId:current?.id||'_environment',sourceName:'',label:'',outcome:kind==='damage'?'hit':'other',roll:'',damageType:'',detail:'',targets:target?[target.id]:[]},changes:target?[{id:target.id,effect:kind==='damage'?'damage':kind==='heal'?'heal':'none',amount:1,conditions:target.conditions,changeConditions:kind==='condition'}]:[]});}
 function changeAction(values:Partial<CombatAction>){setAction(d=>d?{...d,action:{...d.action,...values}}:d);}
 function changeTarget(id:string,values:Partial<Change>){setAction(d=>d?{...d,changes:d.changes.map(c=>c.id===id?{...c,...values}:c)}:d);}
 return <div className="combat-tracker">
  <div className="combat-header"><div><span className="eyebrow">ROUND {board.round} · SOLO DM</span><h2>{current?'Turno di '+current.name:'Prepara il prossimo incontro'}</h2></div><div><IconButton label="Turno precedente" disabled={busy||!sorted.length||(board.round===1&&index===0)} onClick={()=>nextTurn(-1)}><ChevronLeft size={19}/></IconButton><button className="btn primary" disabled={busy||!sorted.length} onClick={()=>nextTurn(1)}>Turno successivo<ChevronRight size={17}/></button></div></div>
  <div className="combat-toolbar"><button className="btn outline" disabled={busy||sorted.length>=100} onClick={()=>open()}><Plus size={16}/>Combattente</button><button className="btn outline" disabled={busy} onClick={()=>{setBase({board,version});setLibrary(true);}}><BookMarked size={16}/>Bestiario</button><button className="btn primary" disabled={busy||!sorted.length} onClick={()=>record()}><ScrollText size={16}/>Registra azione</button><button className="btn outline" disabled={busy||!board.log?.events.length} onClick={()=>{setBase({board,version});setError('');setArchive(true);}}><Archive size={16}/>Concludi e archivia</button></div>
  <p className="help-text">Ogni azione si salva insieme alle sue conseguenze. Usa «Registra azione» anche per attacchi mancati, magie, reazioni e azioni senza danni.</p>
  {error&&<p role="alert" className="form-error">{error}</p>}
  {sorted.length?<Table className="combat-table"><TableHeader><TableRow><TableHead>INIT.</TableHead><TableHead>COMBATTENTE</TableHead><TableHead>CA</TableHead><TableHead>PUNTI FERITA</TableHead><TableHead>CONDIZIONI</TableHead><TableHead>GESTIONE</TableHead></TableRow></TableHeader><TableBody>{sorted.map(c=><TableRow key={c.id} className={current?.id===c.id?'current-turn':''}><TableCell><strong>{c.initiative}</strong></TableCell><TableCell><button className="combat-name" disabled={busy} onClick={()=>open(c)}>{c.name}</button>{c.notes&&<small className="combat-note">{c.notes}</small>}</TableCell><TableCell>{c.ac}</TableCell><TableCell><div className="hp-controls"><button aria-label={'Danneggia '+c.name} disabled={busy} onClick={()=>record('damage',c)}>−</button><strong className={c.hp===0?'hp-zero':''}>{c.hp}<span> / {c.maxHp}</span></strong><button aria-label={'Cura '+c.name} disabled={busy} onClick={()=>record('heal',c)}>+</button></div></TableCell><TableCell><button className="condition-button" disabled={busy} onClick={()=>record('condition',c)}>{c.conditions||'Nessuna'}</button></TableCell><TableCell><div className="combat-row-actions"><IconButton label={'Modifica '+c.name} disabled={busy} onClick={()=>open(c)}><Pencil size={15}/></IconButton><IconButton label={'Salva '+c.name+' nel bestiario'} disabled={busy||bestiary.creatures.length>=200||bestiary.creatures.some(x=>x.name===c.name)} onClick={()=>void perform(()=>onSaveBestiary({creatures:[...bestiary.creatures,{...c,id:crypto.randomUUID()}]},bestiaryVersion))}><Star size={15}/></IconButton><IconButton label={'Duplica '+c.name} disabled={busy||sorted.length>=100} onClick={()=>void commit({...board,combatants:[...board.combatants,{...c,id:crypto.randomUUID(),name:c.name+' (2)'}]})}><Copy size={15}/></IconButton><IconButton label={'Rimuovi '+c.name} disabled={busy} onClick={()=>{setBase({board,version});setRemoveId(c.id);}}><Trash2 size={15}/></IconButton></div></TableCell></TableRow>)}</TableBody></Table>:<div className="empty-page"><Swords size={34}/><h2>Un incontro da raccontare</h2><p>Aggiungi i combattenti, poi registra ciò che accade. Alla fine, il resoconto entrerà nell’archivio della campagna.</p></div>}
  <CombatLog events={board.log?.events||[]} compact/>
  <Dialog open={!!draft} onOpenChange={v=>{if(!v&&!busy)setDraft(null);}}><DialogContent><DialogHeader><DialogTitle>{draft&&base.board.combatants.some(c=>c.id===draft.id)?'Modifica combattente':'Aggiungi combattente'}</DialogTitle><DialogDescription>Classe armatura, punti ferita e note della scheda restano riservati al DM.</DialogDescription></DialogHeader>{draft&&<form onSubmit={async e=>{e.preventDefault();const exists=base.board.combatants.some(c=>c.id===draft.id);const combatants=exists?base.board.combatants.map(c=>c.id===draft.id?draft:c):[...base.board.combatants,draft];if(await commit({...base.board,combatants,turnId:base.board.turnId||draft.id},base.version))setDraft(null);}}><label className="field">Nome<input required maxLength={100} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><div className="form-grid">{[{key:'initiative',label:'Iniziativa',min:-100,max:100},{key:'ac',label:'Classe armatura',min:0,max:100},{key:'hp',label:'PF attuali',min:0,max:100000},{key:'maxHp',label:'PF massimi',min:Math.max(1,draft.hp),max:100000}].map(f=><label className="field" key={f.key}>{f.label}<input type="number" required min={f.min} max={f.max} disabled={f.key==='hp'&&base.board.combatants.some(c=>c.id===draft.id)} value={draft[f.key as keyof Combatant]} onChange={e=>setDraft({...draft,[f.key]:+e.target.value})}/></label>)}</div>{!base.board.combatants.some(c=>c.id===draft.id)&&<label className="field">Condizioni iniziali<input maxLength={250} value={draft.conditions} onChange={e=>setDraft({...draft,conditions:e.target.value})}/></label>}<p className="help-text">Per cambiare PF o condizioni di un combattente già in campo, registra un’azione: la fonte resterà nel resoconto.</p><label className="field">Note private<textarea maxLength={1000} rows={3} value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})}/></label>{error&&<p role="alert" className="form-error">{error}</p>}<button className="btn primary" disabled={busy}>Salva combattente</button></form>}</DialogContent></Dialog>
  <Dialog open={!!action} onOpenChange={v=>{if(!v&&!busy)setAction(null);}}><DialogContent className="combat-action-dialog"><DialogHeader><DialogTitle>Registra azione</DialogTitle><DialogDescription>Indica chi agisce, l’esito e le conseguenze. Puoi coinvolgere più bersagli nella stessa azione.</DialogDescription></DialogHeader>{action&&<form onSubmit={async e=>{e.preventDefault();const a=action.action;const changed=action.changes;const combatants=action.board.combatants.map(c=>{const t=changed.find(t=>t.id===c.id);return t?{...c,hp:t.effect==='damage'?Math.max(0,c.hp-t.amount):t.effect==='heal'?Math.min(c.maxHp,c.hp+t.amount):c.hp,conditions:t.changeConditions?t.conditions:c.conditions}:c;});const requested=changed.filter(t=>t.effect!=='none').map(t=>({id:t.id,kind:t.effect as 'damage'|'heal',amount:t.amount}));if(await commit({...action.board,combatants},action.version,{...a,targets:changed.map(t=>t.id),requested}))setAction(null);}}>
   <div className="form-grid"><label className="field">Tipo<Choice value={action.action.kind} onChange={kind=>changeAction({kind:kind as CombatAction['kind']})} options={Object.entries(ACTION_KINDS).map(([value,label])=>({value,label}))}/></label><label className="field">Chi agisce / fonte<Choice value={action.action.sourceId} onChange={sourceId=>changeAction({sourceId})} options={[...action.board.combatants.map(c=>({value:c.id,label:c.name})),{value:'_environment',label:'Ambiente'},{value:'_other',label:'Altra fonte'}]}/></label></div>
   {action.action.sourceId==='_other'&&<label className="field">Nome della fonte<input required maxLength={100} value={action.action.sourceName} onChange={e=>changeAction({sourceName:e.target.value})}/></label>}
   <label className="field">Attacco, magia o azione<input required maxLength={160} placeholder="Es. morso, dardo di fuoco, caduta, azione di Aiuto…" value={action.action.label} onChange={e=>changeAction({label:e.target.value})}/></label>
   <div className="form-grid"><label className="field">Esito<Choice value={action.action.outcome} onChange={outcome=>{changeAction({outcome:outcome as CombatAction['outcome']});if(outcome==='miss')setAction(d=>d?{...d,changes:d.changes.map(t=>({...t,effect:'none',changeConditions:false}))}:d);}} options={Object.entries(OUTCOMES).map(([value,label])=>({value,label}))}/></label><label className="field">Tiro e risultato (facoltativo)<input maxLength={100} placeholder="Es. 17 contro CA 15; TS 12 fallito" value={action.action.roll} onChange={e=>changeAction({roll:e.target.value})}/></label><label className="field">Tipo di danno (facoltativo)<input maxLength={80} placeholder="Es. fuoco, tagliente, necrotico" value={action.action.damageType} onChange={e=>changeAction({damageType:e.target.value})}/></label></div>
   <fieldset className="combat-target-editor"><legend>Bersagli e conseguenze</legend><p className="help-text">Seleziona chi è coinvolto. Lascia «Nessun danno o cura» per azioni senza variazioni di PF.</p>{action.board.combatants.map(c=>{const t=action.changes.find(t=>t.id===c.id);return <div key={c.id} className={'combat-target-row '+(t?'selected':'')}><Check checked={!!t} onChange={checked=>setAction(d=>d?{...d,changes:checked?[...d.changes,{id:c.id,effect:'none',amount:0,conditions:c.conditions,changeConditions:false}]:d.changes.filter(x=>x.id!==c.id)}:d)}>{c.name}</Check>{t&&<div className="combat-target-fields"><label className="field">Effetto sui PF<Choice disabled={action.action.outcome==='miss'} value={t.effect} onChange={effect=>changeTarget(c.id,{effect:effect as Change['effect']})} options={[{value:'none',label:'Nessun danno o cura'},{value:'damage',label:'Danno'},{value:'heal',label:'Cura'}]}/></label>{t.effect!=='none'&&<label className="field">Quantità<input type="number" required min={0} max={100000} value={t.amount} onChange={e=>changeTarget(c.id,{amount:+e.target.value})}/></label>}<Check disabled={action.action.outcome==='miss'} checked={t.changeConditions} onChange={changeConditions=>changeTarget(c.id,{changeConditions})}>Aggiorna condizioni</Check>{t.changeConditions&&<label className="field">Condizioni dopo l’azione<input maxLength={250} value={t.conditions} placeholder="Vuoto per rimuovere tutte le condizioni" onChange={e=>changeTarget(c.id,{conditions:e.target.value})}/></label>}</div>}</div>;})}</fieldset>
   <label className="field">Descrizione / altre conseguenze<textarea rows={3} maxLength={1500} placeholder="Movimento, concentrazione, reazioni, dettagli narrativi…" value={action.action.detail} onChange={e=>changeAction({detail:e.target.value})}/></label>{error&&<p role="alert" className="form-error">{error}</p>}<div className="editor-actions"><button type="button" className="btn ghost" disabled={busy} onClick={()=>setAction(null)}>Annulla</button><button className="btn primary" disabled={busy}>{busy?'Salvataggio…':'Registra azione e conseguenze'}</button></div>
  </form>}</DialogContent></Dialog>
  <Dialog open={library} onOpenChange={v=>{if(!busy)setLibrary(v);}}><DialogContent><DialogHeader><DialogTitle>Bestiario</DialogTitle><DialogDescription>Avversari salvati, visibili solo al DM.</DialogDescription></DialogHeader><label className="field">Copie da aggiungere<input type="number" min={1} max={20} value={copies} onChange={e=>setCopies(Math.max(1,Math.min(20,+e.target.value||1)))}/></label>{bestiary.creatures.map(c=><div className="bestiary-row" key={c.id}><div><strong>{c.name}</strong><small>CA {c.ac} · {c.maxHp} PF</small></div><button className="btn outline compact" disabled={busy||base.board.combatants.length+copies>100} onClick={async()=>{const added=Array.from({length:copies},(_,i)=>({...c,id:crypto.randomUUID(),name:copies>1?c.name+' '+(i+1):c.name,hp:c.maxHp}));if(await commit({...base.board,combatants:[...base.board.combatants,...added],turnId:base.board.turnId||added[0].id},base.version))setLibrary(false);}}>In campo</button><IconButton label={'Togli '+c.name+' dal bestiario'} disabled={busy} onClick={()=>void perform(()=>onSaveBestiary({creatures:bestiary.creatures.filter(x=>x.id!==c.id)},bestiaryVersion))}><Trash2 size={15}/></IconButton></div>)}{!bestiary.creatures.length&&<p className="help-text">Salva un combattente con la stella accanto al suo nome.</p>}{error&&<p className="form-error">{error}</p>}</DialogContent></Dialog>
  <Dialog open={archive} onOpenChange={v=>{if(!busy)setArchive(v);}}><DialogContent><DialogHeader><DialogTitle>Concludi e archivia</DialogTitle><DialogDescription>Il registro verrà salvato come pagina privata e l’iniziativa sarà liberata per il prossimo incontro. Potrai poi aggiungere descrizione, immagini e scegliere chi può leggerlo.</DialogDescription></DialogHeader><form onSubmit={async e=>{e.preventDefault();if(await perform(()=>onArchive({version:base.version,encounterId:base.board.log?.id,title,links}))){setArchive(false);setTitle('');setLinks([]);}}}><label className="field">Titolo del combattimento<input required maxLength={160} value={title} placeholder="Es. L’imboscata sulla strada di Vallaki" onChange={e=>setTitle(e.target.value)}/></label><fieldset className="archive-links"><legend>Collega alla campagna</legend>{records.filter(r=>['journal','event','pin','map','character'].includes(r.kind)).map(r=><Check key={r.id} checked={links.includes(r.id)} onChange={checked=>setLinks(ids=>checked?[...ids,r.id]:ids.filter(id=>id!==r.id))}>{r.title}</Check>)}</fieldset><p className="help-text">Vengono condivise soltanto le azioni registrate. CA, PF totali e note private delle schede restano nello schermo DM; nomi, danni, condizioni e descrizioni delle azioni fanno parte del resoconto.</p>{error&&<p role="alert" className="form-error">{error}</p>}<button className="btn primary" disabled={busy}>Salva Combat Log privato</button></form></DialogContent></Dialog>
  <AlertDialog open={!!removeId} onOpenChange={v=>{if(!v&&!busy)setRemoveId('');}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Rimuovere il combattente?</AlertDialogTitle><AlertDialogDescription>Uscirà dall’ordine di iniziativa. Le sue azioni resteranno nel registro.</AlertDialogDescription></AlertDialogHeader>{error&&<p className="form-error">{error}</p>}<AlertDialogFooter><AlertDialogCancel disabled={busy}>Annulla</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={async e=>{e.preventDefault();if(await commit(removeCombatant(base.board,removeId),base.version))setRemoveId('');}}>Rimuovi dall’incontro</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </div>;
}
