import React,{useMemo,useState} from 'react';
import {ArrowUpRight,BookOpen,ChevronRight,Clock3,LockKeyhole,Search,Shield,Swords,Users,X} from 'lucide-react';
import {Choice} from './ui';
import {dateLabel,type Entry,type State} from '@/lib/campaign';
import type {CombatEvent} from '@/lib/combat';

function summary(entry:Entry){
 const events=(Array.isArray(entry.data.events)?entry.data.events:[]) as CombatEvent[];
 const actions=events.filter(e=>e.kind!=='turn'&&e.kind!=='setup');
 const names=Array.from(new Set(events.flatMap(e=>[...(e.kind!=='turn'&&e.kind!=='setup'?[e.sourceName]:[]),...e.targets,...e.effects.map(f=>f.targetName)]).filter(Boolean)));
 return {actions:actions.length,names,events};
}
function excerpt(text:string){return text.replace(/\[\[([^\]|]+)(?:\|([^\]]*))?\]\]/g,(_token,_id,label)=>label||'riferimento').replace(/^#+\s*/gm,'').replace(/\s+/g,' ').trim();}
export default function CombatArchive({state,onOpen,onManage,tag,onTagChange:setTag}:{state:State;tag:string;onTagChange:(tag:string)=>void;onOpen:(entry:Entry)=>void;onManage:()=>void}){
 const [query,setQuery]=useState('');const [sort,setSort]=useState('campaign');const [visibility,setVisibility]=useState('all');const [limit,setLimit]=useState(12);
 const all=useMemo(()=>state.records.filter(r=>r.kind==='combat').map(entry=>({entry,...summary(entry)})),[state.records]);
 const labels=useMemo(()=>Array.from(new Set(all.flatMap(({entry})=>entry.data.tags||[]))).sort(),[all]);
 const filtered=useMemo(()=>all.filter(({entry,names})=>(!query||(entry.title+' '+excerpt(entry.body)+' '+names.join(' ')).toLocaleLowerCase('it').includes(query.trim().toLocaleLowerCase('it')))&&(!tag||(entry.data.tags||[]).includes(tag))&&(visibility==='all'||(visibility==='shared'?entry.audience.some(id=>id!==entry.owner):!entry.audience.some(id=>id!==entry.owner)))).sort((a,b)=>sort==='updated'?b.entry.updated-a.entry.updated:(b.entry.data.minutes||0)-(a.entry.data.minutes||0)||b.entry.updated-a.entry.updated),[all,query,tag,sort,visibility]);
 const isDM=state.user.role==='dm';const filteredOn=!!query||!!tag||visibility!=='all';
 function reset(){setQuery('');setTag('');setVisibility('all');setLimit(12);}
 return <div className="content-page combat-archive-page">
  <header className="archive-masthead"><div><span className="eyebrow">ARCHIVIO DEGLI INCONTRI</span><h1>Resoconti di<br/><em>combattimento</em></h1><p>Consulta le azioni registrate, i resoconti e le pagine collegate.</p></div><div className="archive-seal" aria-hidden="true"><Swords strokeWidth={1}/><span>BAROVIA</span><i>COMBAT LOG</i></div></header>
  <div className="archive-ledger"><span><strong>{all.length.toLocaleString('it-IT')}</strong>{all.length===1?'resoconto':'resoconti'} nell’archivio</span><span><strong>{all.reduce((n,r)=>n+r.actions,0).toLocaleString('it-IT')}</strong>azioni registrate</span>{isDM?<button className="btn outline" onClick={onManage}><Shield size={16}/>Apri gli incontri<ArrowUpRight size={16}/></button>:<p><Users size={16}/>I combattimenti condivisi con te</p>}</div>
  <div className="archive-controls"><label className="search-field"><Search size={18}/><input aria-label="Cerca nei combattimenti" placeholder="Cerca un incontro, un combattente o una descrizione…" value={query} onChange={e=>{setQuery(e.target.value);setLimit(12);}}/>{query&&<button className="archive-clear" aria-label="Cancella ricerca" onClick={()=>setQuery('')}><X size={15}/></button>}</label><Choice label="Ordina i combattimenti" value={sort} onChange={setSort} options={[{value:'campaign',label:'Data della campagna'},{value:'updated',label:'Ultime modifiche'}]}/>{isDM&&<Choice label="Visibilità dei combattimenti" value={visibility} onChange={v=>{setVisibility(v);setLimit(12);}} options={[{value:'all',label:'Tutti i resoconti'},{value:'private',label:'Solo privati'},{value:'shared',label:'Condivisi'}]}/>}</div>
  {!!labels.length&&<div className="tag-filter archive-tags" aria-label="Filtra per etichetta"><button className={!tag?'selected':''} onClick={()=>{setTag('');setLimit(12);}}>Tutte le etichette</button>{labels.map(label=><button key={label} className={tag===label?'selected':''} onClick={()=>{setTag(tag===label?'':label);setLimit(12);}}>{label}</button>)}</div>}
  <div className="archive-list-heading"><span className="eyebrow">{filteredOn?'RISULTATI NELL’ARCHIVIO':'I RESOCONTI DELLA CAMPAGNA'}</span><span>{filtered.length} {filtered.length===1?'pagina':'pagine'}</span>{filteredOn&&<button className="text-button" onClick={reset}>Azzera filtri<X size={13}/></button>}</div>
  {!filtered.length?<section className="archive-empty"><div className="archive-empty-icon"><Swords size={38} strokeWidth={1}/></div><span className="eyebrow">{all.length?'NESSUNA CORRISPONDENZA':'ARCHIVIO VUOTO'}</span><h2>{all.length?'Nessun incontro con questi filtri.':'Nessun combattimento archiviato.'}</h2><p>{all.length?'Prova un altro nome, oppure torna all’archivio completo.':isDM?'Registra le azioni nello schermo DM e concludi l’incontro per archiviarlo. Potrai aggiungere descrizione e immagini e scegliere con chi condividerlo.':'Qui compaiono i resoconti dei combattimenti condivisi con te dal DM.'}</p>{all.length?<button className="btn outline" onClick={reset}>Mostra tutti gli incontri</button>:isDM&&<button className="btn primary" onClick={onManage}><Swords size={16}/>Prepara il primo incontro</button>}</section>:<div className="combat-archive-grid">{filtered.slice(0,limit).map(({entry,names,actions},i)=>{
   const image=entry.data.images?.[0];const privateEntry=!entry.audience.some(id=>id!==entry.owner);const linked=state.records.filter(r=>['journal','event','pin','map'].includes(r.kind)&&(entry.links.includes(r.id)||r.links.includes(entry.id)));
   return <article key={entry.id} className={'combat-story-card '+(i===0&&!filteredOn?'featured':'')}><button className="combat-story-open" onClick={()=>onOpen(entry)} aria-label={'Leggi '+entry.title}><div className={'combat-story-cover '+(image?'has-image':'')}>
    {image?<img src={'/api/media/'+image.id} alt="" loading="lazy" decoding="async"/>:<><span className="cover-orbit"/><Swords size={48} strokeWidth={.8}/><span className="cover-label">RESOCONTO DEL COMBATTIMENTO</span></>}
    <span className="combat-privacy">{privateEntry?<LockKeyhole size={12}/>:<Users size={12}/>}<span>{privateEntry?'Privato':'Condiviso'}</span></span><span className="cover-read">Leggi il resoconto<ArrowUpRight size={17}/></span>
   </div><div className="combat-story-copy"><div className="combat-story-date"><Clock3 size={13}/>{dateLabel(entry.data.minutes||0,state.settings.months)}</div><h2>{entry.title}</h2><p>{excerpt(entry.body).slice(0,i===0?230:145)||'Consulta le azioni registrate per questo incontro.'}</p><div className="combat-story-facts"><span>{entry.data.rounds||1} round</span><i/><span>{actions} azioni</span><i/><span>{names.length} fonti e combattenti</span></div>{!!names.length&&<div className="combat-cast">{names.slice(0,3).map(n=><span key={n}>{n}</span>)}{names.length>3&&<span>+{names.length-3}</span>}</div>}</div></button>
   {!!linked.length&&<footer className="combat-story-links"><BookOpen size={14}/><span className="sr-only">Pagine collegate</span>{linked.slice(0,2).map(r=><button key={r.id} onClick={()=>onOpen(r)}>{r.title}<ChevronRight size={13}/></button>)}{linked.length>2&&<span>+{linked.length-2} collegamenti</span>}</footer>}
  </article>;})}</div>}
  {filtered.length>limit&&<div className="archive-more"><button className="btn outline" onClick={()=>setLimit(n=>n+12)}>Altri resoconti<ChevronRight size={16}/></button><span>{Math.min(limit,filtered.length)} di {filtered.length}</span></div>}
 </div>;
}
