'use client';
import RichTextEditor from './rich-text-editor';
import {ImageField,GalleryEditor,uploadImage} from './image-fields';
import React,{useState,useEffect,useRef} from 'react';
import { Plus, Link2, Users, LockKeyhole, ImagePlus, MapPin, X, Search, Clock3, Layers, Dices, GripVertical } from 'lucide-react';
import { Dialog, DialogContent, DialogTitle, DialogHeader, DialogDescription } from '@/components/ui/dialog';
import { Command, CommandInput, CommandList, CommandEmpty, CommandItem } from '@/components/ui/command';
import { Slider } from '@/components/ui/slider';
import { toast } from 'sonner';
import { Check,Choice,DateEditor,TagField } from './ui';
import { KINDS,COINS,type Entry,type State } from '@/lib/campaign';
/** Bozza tenuta nel browser mentre si scrive: se il salvataggio va storto, se la scheda
 *  si chiude o se qualcuno modifica la stessa voce, il testo non è perso.
 *  La chiave include la versione, così una bozza vecchia non copre una voce già aggiornata. */
const draftKey=(e:Entry)=>'barovia-bozza:'+(e.id||'nuova-'+e.kind);
function readDraft(entry:Entry):Entry|null{
 try{const raw=localStorage.getItem(draftKey(entry));if(!raw)return null;
  const saved=JSON.parse(raw) as {at:number;version:number;draft:Entry};
  if(!saved?.draft||saved.version!==entry.version||Date.now()-saved.at>604800000)return null;
  return JSON.stringify(saved.draft)===JSON.stringify(entry)?null:saved.draft;
 }catch{return null;}
}
function writeDraft(entry:Entry,draft:Entry){try{localStorage.setItem(draftKey(entry),JSON.stringify({at:Date.now(),version:entry.version,draft}));}catch{/* spazio esaurito o accesso negato: la bozza è un extra */}}
function clearDraft(entry:Entry){try{localStorage.removeItem(draftKey(entry));}catch{/* vedi sopra */}}
export default function EntryEditor({entry,state,onClose,onSave,onPosition}:{entry:Entry;state:State;onClose:()=>void;onSave:(e:Entry)=>Promise<void>;onPosition:(e:Entry)=>void}){
 const [recovered]=useState(()=>readDraft(entry));const [restored,setRestored]=useState(false);
 const [draft,setDraft]=useState(entry);const [busy,setBusy]=useState(false);const [uploadCount,setUploadCount]=useState(0);const uploading=uploadCount>0;function setUploading(value:boolean){setUploadCount(n=>Math.max(0,n+(value?1:-1)));}const [error,setError]=useState('');
 const owner=entry.owner===state.user.id;const update=(changes:Partial<Entry>)=>setDraft(d=>({...d,...changes}));const data=(changes:any)=>setDraft(d=>({...d,data:{...d.data,...changes}}));const kind=draft.kind;
 async function upload(file:File){setUploading(true);try{const id=await uploadImage(file);data({image:id});toast.success('Immagine caricata');}catch(e){toast.error((e as Error).message);}finally{setUploading(false);}}
 // Le proporzioni della mappa si ricavano dall'immagine appena scelta.
 useEffect(()=>{if(kind!=='map'||!draft.data.image)return;let alive=true;const img=new Image();
  img.onload=()=>{if(alive&&img.naturalWidth&&img.naturalHeight)data({ratio:img.naturalWidth/img.naturalHeight});};
  img.src='/api/media/'+draft.data.image;return()=>{alive=false;};},[kind,draft.data.image]);
 const dirty=useRef(false);
 useEffect(()=>{if(draft===entry)return;dirty.current=true;const timer=setTimeout(()=>writeDraft(entry,draft),800);return()=>clearTimeout(timer);},[draft,entry]);
 useEffect(()=>{const guard=()=>{if(dirty.current)writeDraft(entry,draft);};window.addEventListener('pagehide',guard);return()=>window.removeEventListener('pagehide',guard);},[draft,entry]);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await onSave(draft);clearDraft(entry);dirty.current=false;onClose();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <Dialog open onOpenChange={v=>{if(!v&&!busy)onClose();}}><DialogContent className="editor-dialog"><DialogHeader><div className="eyebrow">{entry.version?'MODIFICA':'NUOVO CONTENUTO'} · {KINDS[kind].label.toUpperCase()}</div><DialogTitle>{(entry.version?'Modifica: ':'Nuovo contenuto: ')+KINDS[kind].label.toLowerCase()}</DialogTitle><DialogDescription>{kind==='secret'?'Uno spazio riservato al Dungeon Master.':'Modifica il contenuto, gli allegati e la visibilità.'}</DialogDescription></DialogHeader>
 <form onSubmit={submit} className="editor-form">{recovered&&!restored&&<div className="draft-recovery"><div><strong>Bozza non salvata</strong><span>Da questa voce erano rimaste delle modifiche nel browser.</span></div><div className="draft-recovery-actions"><button type="button" className="btn outline compact" onClick={()=>{setDraft(recovered);setRestored(true);}}>Recupera</button><button type="button" className="btn ghost compact" onClick={()=>{clearDraft(entry);setRestored(true);}}>Ignora</button></div></div>}<label className="field">Titolo<input autoFocus required maxLength={160} placeholder={kind==='character'?'Nome del personaggio':kind==='pin'?'Nome del luogo':'Titolo'} value={draft.title} onChange={e=>update({title:e.target.value})}/></label>
 {kind==='character'&&<div className="form-grid"><label className="field">Ruolo o descrizione breve<input value={draft.data.subtitle||''} onChange={e=>data({subtitle:e.target.value})} placeholder="Es. mercante di Vallaki"/></label><label className="field">Stato<Choice value={draft.data.status||'Sconosciuto'} onChange={v=>data({status:v})} options={['Sconosciuto','In vita','Scomparso','Deceduto'].map(v=>({value:v,label:v}))}/></label><div className="image-upload">{draft.data.image?<><img src={'/api/media/'+draft.data.image} alt="Ritratto del personaggio"/><button type="button" className="text-button" onClick={()=>data({image:''})}><X size={15}/>Rimuovi immagine</button></>:<label className="upload-button"><ImagePlus size={21}/><span>{uploading?'Caricamento…':'Aggiungi un ritratto'}</span><small>PNG, JPEG o WebP · fino a 4 MB</small><input type="file" accept="image/png,image/jpeg,image/webp" disabled={uploading} onChange={e=>{if(e.target.files?.[0])void upload(e.target.files[0]);}}/></label>}</div></div>}
 {kind==='character'&&<section className="sheet-editor"><Check checked={draft.data.pc===true} onChange={v=>data({pc:v})}>È un personaggio del gruppo (mostra la scheda)</Check>
 {draft.data.pc===true&&<><div className="form-grid"><label className="field">Giocatore<input value={draft.data.player||''} onChange={e=>data({player:e.target.value})} placeholder="Chi lo interpreta"/></label><label className="field">Classe e stirpe<input value={draft.data.role||''} onChange={e=>data({role:e.target.value})} placeholder="Es. chierico umano"/></label></div>
 <div className="sheet-grid"><label className="field">Livello<input type="number" min={1} max={30} value={draft.data.level??1} onChange={e=>data({level:+e.target.value})}/></label><label className="field">PF attuali<input type="number" min={-999} max={9999} value={draft.data.hp??0} onChange={e=>data({hp:+e.target.value})}/></label><label className="field">PF massimi<input type="number" min={0} max={9999} value={draft.data.maxHp??0} onChange={e=>data({maxHp:+e.target.value})}/></label><label className="field">CA<input type="number" min={0} max={99} value={draft.data.ac??10} onChange={e=>data({ac:+e.target.value})}/></label><label className="field">Percezione passiva<input type="number" min={0} max={99} value={draft.data.passive??10} onChange={e=>data({passive:+e.target.value})}/></label><label className="field">Velocità (m)<input type="number" min={0} max={999} value={draft.data.speed??9} onChange={e=>data({speed:+e.target.value})}/></label></div></>}
 </section>}
 {kind==='map'&&<section className="map-editor">
  <ImageField value={draft.data.image||''} label="Immagine della mappa" onBusy={setUploading} onChange={v=>data({image:v})}/>
  <p className="help-text">Le proporzioni vengono lette dall’immagine appena caricata, così la mappa non risulta schiacciata.</p>
  <div className="form-grid"><label className="field">Larghezza reale in miglia<input type="number" min={.001} step=".1" value={draft.data.widthMiles??1} onChange={e=>data({widthMiles:+e.target.value})}/></label><label className="field">Mappa che la contiene<Choice value={draft.data.parent||''} onChange={v=>data({parent:v})} options={[{value:'',label:'Barovia · mappa principale'},...state.records.filter(r=>r.kind==='map'&&r.id!==draft.id).map(r=>({value:r.id,label:r.title}))]}/></label></div>
  <p className="help-text">Sulla mappa che la contiene compare una porta d’accesso in questa posizione. Apri quella mappa e usa «Scegli sulla mappa» per spostarla.</p>
 </section>}
 {kind==='table'&&<section className="table-editor">
  <label className="field">Come si tira<input value={draft.data.dice||''} placeholder="Es. 1d12 · incontri notturni" maxLength={20} onChange={e=>data({dice:e.target.value})}/></label>
  <div className="row-between"><label><Dices size={16}/>Risultati <span className="count">{(draft.data.entries||[]).length}/200</span></label><button type="button" className="btn outline compact" onClick={()=>data({entries:[...(draft.data.entries||[]),{id:crypto.randomUUID(),text:''}]})}><Plus size={15}/>Aggiungi riga</button></div>
  <div className="table-rows">{(draft.data.entries||[]).map((row:any,i:number)=><div className="table-row-edit" key={row.id}><span className="table-row-number">{i+1}</span><input value={row.text} maxLength={300} placeholder="Cosa succede" onChange={e=>data({entries:draft.data.entries.map((r:any,j:number)=>i===j?{...r,text:e.target.value}:r)})}/><button type="button" aria-label={'Togli la riga '+(i+1)} onClick={()=>data({entries:draft.data.entries.filter((_:any,j:number)=>j!==i)})}><X size={15}/></button></div>)}</div>
  {!(draft.data.entries||[]).length&&<p className="help-text">Aggiungi una riga per ogni risultato possibile. Si tira un dado con tante facce quante sono le righe.</p>}
 </section>}
 {kind==='pin'&&<><ImageField value={draft.data.markerImage||''} label="Immagine del segnalino" onBusy={setUploading} onChange={v=>data({markerImage:v})}/><label className="field">Icona del segnalino<Choice value={draft.data.markerIcon||'pin'} onChange={v=>data({markerIcon:v})} options={[{value:'pin',label:'Segnaposto'},{value:'castle',label:'Castello'},{value:'town',label:'Insediamento'},{value:'trees',label:'Bosco'},{value:'skull',label:'Pericolo'},{value:'clue',label:'Indizio'}]}/></label></>}
 {kind==='pin'&&<label className="field">Tipo di luogo<Choice value={draft.data.category||'luogo'} onChange={v=>data({category:v})} options={[{value:'luogo',label:'Punto di interesse'},{value:'insediamento',label:'Insediamento'},{value:'natura',label:'Natura'},{value:'pericolo',label:'Pericolo'},{value:'indizio',label:'Indizio'}]}/></label>}
 {kind==='event'&&<DateEditor value={draft.data.minutes??state.settings.minutes} onChange={v=>data({minutes:v})} settings={state.settings}/>}
 {(kind==='pin'||kind==='event'||kind==='map')&&<div className="position-fields"><button className="btn outline" type="button" onClick={()=>onPosition(draft)}><MapPin size={16}/>Scegli sulla mappa</button><label>X %<input aria-label="Coordinata X in percentuale" type="number" min={0} max={100} step=".1" value={Math.round((draft.data.x??.5)*1000)/10} onChange={e=>data({x:+e.target.value/100})}/></label><label>Y %<input aria-label="Coordinata Y in percentuale" type="number" min={0} max={100} step=".1" value={Math.round((draft.data.y??.5)*1000)/10} onChange={e=>data({y:+e.target.value/100})}/></label></div>}
 {kind==='journal'&&<div className="form-grid"><label className="field">Numero sessione<input type="number" min={1} value={draft.data.session||1} onChange={e=>data({session:+e.target.value})}/></label><label className="field">Data della sessione<input type="date" value={draft.data.date||''} onChange={e=>data({date:e.target.value})}/></label></div>}
 {kind==='journal'&&<details className="session-window"><summary><Clock3 size={16}/>Quando accade nella campagna <span className="count">{draft.data.minutes!==undefined?'impostato':'facoltativo'}</span></summary><p className="help-text">Indicando l’inizio e la fine, nella pagina della sessione compaiono gli eventi della cronologia accaduti in quel periodo.</p><label className="field">Inizio<DateEditor value={draft.data.minutes??state.settings.minutes} onChange={v=>data({minutes:v})} settings={state.settings}/></label><label className="field">Fine<DateEditor value={draft.data.endMinutes??draft.data.minutes??state.settings.minutes} onChange={v=>data({endMinutes:v})} settings={state.settings}/></label>{draft.data.minutes!==undefined&&<button type="button" className="text-button" onClick={()=>setDraft(d=>{const next={...d.data};delete next.minutes;delete next.endMinutes;return{...d,data:next};})}>Togli il collegamento con la cronologia</button>}</details>}
 {kind==='treasure'&&<div className="form-grid"><label className="field">Quantità<input type="number" min={0} step="1" value={draft.data.quantity??1} onChange={e=>data({quantity:+e.target.value})}/></label><label className="field">Valore unitario<input type="number" min={0} step=".01" value={draft.data.value??0} onChange={e=>data({value:+e.target.value})}/></label><label className="field">Moneta<Choice value={draft.data.currency||'mo'} onChange={v=>data({currency:v})} options={COINS.map(c=>({value:c.id,label:c.label+' ('+c.id+')'}))}/></label><label className="field">Custode<input value={draft.data.holder||''} placeholder="Gruppo o nome del personaggio" onChange={e=>data({holder:e.target.value})}/></label><label className="field">Categoria<input value={draft.data.category||''} placeholder="Es. arma, pozione, monete" onChange={e=>data({category:e.target.value})}/></label></div>}
 {kind==='faction'&&<><label className="field">Dettaglio o referente<input value={draft.data.subtitle||''} placeholder="Referente, luogo, obiettivo…" onChange={e=>data({subtitle:e.target.value})}/></label><div className="reputation-editor"><div className="row-between"><label>Reputazione del gruppo</label><strong>{draft.data.reputation??0}</strong></div><Slider aria-label="Reputazione" min={-100} max={100} step={1} value={[draft.data.reputation??0]} onValueChange={([v])=>data({reputation:v})}/><div className="row-between small muted"><span>Ostile −100</span><span>Neutrale 0</span><span>Alleata +100</span></div></div></>}
 <RichTextEditor label={kind==='journal'?'Riepilogo della sessione':'Descrizione e appunti'} value={draft.body} onChange={body=>update({body})} records={state.records.filter(r=>r.id!==draft.id)}/>{kind!=='folder'&&<GalleryEditor images={draft.data.images||[]} onChange={images=>data({images})} onBusy={setUploading}/>}
 {kind==='secret'&&<><label className="field">Sezione<Choice value={draft.data.section||'session'} onChange={v=>data({section:v})} options={[{value:'session',label:'Preparazione sessione'},{value:'scene',label:'Scene e incontri'},{value:'npc',label:'Personaggi'},{value:'clue',label:'Indizi e segreti'},{value:'rules',label:'Riferimenti e regole'}]}/></label><Check checked={draft.data.pinned===true} onChange={v=>data({pinned:v})}>In evidenza nello schermo DM</Check><div className="task-editor"><label>Checklist</label>{(draft.data.tasks||[]).map((task:any,i:number)=><div key={task.id}><Check checked={task.done} onChange={done=>data({tasks:draft.data.tasks.map((t:any,j:number)=>i===j?{...t,done}:t)})}><span className="sr-only">Completato</span></Check><input aria-label="Attività" value={task.text} onChange={e=>data({tasks:draft.data.tasks.map((t:any,j:number)=>i===j?{...t,text:e.target.value}:t)})}/><button type="button" aria-label="Rimuovi attività" onClick={()=>data({tasks:draft.data.tasks.filter((_:any,j:number)=>i!==j)})}><X size={16}/></button></div>)}<button type="button" className="text-button" onClick={()=>data({tasks:[...(draft.data.tasks||[]),{id:crypto.randomUUID(),text:'',done:false}]})}><Plus size={16}/>Aggiungi attività</button></div></>}
 {kind==='note'&&<label className="field">Cartella<Choice value={draft.folder||'_none'} onChange={v=>update({folder:v==='_none'?'':v})} options={[{value:'_none',label:'Senza cartella'},...state.records.filter(r=>r.kind==='folder').map(r=>({value:r.id,label:r.title}))]}/></label>}
 {kind!=='folder'&&<details className="editor-links"><summary><Link2 size={17}/>Collegamenti <span className="count">{draft.links.length}</span><Plus size={15}/></summary><Command className="link-command"><CommandInput placeholder="Cerca un contenuto da collegare…"/><CommandList><CommandEmpty>Nessun contenuto trovato.</CommandEmpty>{state.records.filter(r=>r.id!==draft.id&&r.kind!=='folder').map(r=><CommandItem key={r.id} value={r.title+' '+r.id} onSelect={()=>update({links:draft.links.includes(r.id)?draft.links.filter(id=>id!==r.id):[...draft.links,r.id]})}><span className={'link-check '+(draft.links.includes(r.id)?'checked':'')}>{draft.links.includes(r.id)?'✓':''}</span><span>{r.title}</span><small>{KINDS[r.kind].label}</small></CommandItem>)}</CommandList></Command><p className="help-text">I collegamenti compaiono in entrambe le pagine e nel grafo. Chi non può leggere una pagina non vedrà il suo collegamento.</p></details>}
 {kind!=='folder'&&<TagField value={draft.data.tags||[]} onChange={tags=>data({tags})} suggestions={Array.from(new Set(state.records.flatMap(r=>r.data.tags||[]))).sort()}/>}
 <div className="visibility-editor"><div className="row-between"><label><Users size={17}/>Visibilità</label>{kind==='secret'?<span className="tag"><LockKeyhole size={13}/>Solo DM</span>:<Choice disabled={!owner} value={draft.audience.includes('*')?'all':'custom'} onChange={v=>update({audience:v==='all'?['*']:[draft.owner]})} options={[{value:'all',label:'Tutto il gruppo'},{value:'custom',label:'Scegli chi può leggere'}]} label="Visibilità"/>}</div>{kind!=='secret'&&!draft.audience.includes('*')&&<div className="audience-grid">{state.users.filter(u=>u.active).map(u=><Check key={u.id} checked={u.id===draft.owner||draft.audience.includes(u.id)} disabled={!owner||u.id===draft.owner} onChange={checked=>update({audience:checked?[...draft.audience,u.id]:draft.audience.filter(id=>id!==u.id)})}>{u.name}{u.id===draft.owner?' · autore':''}</Check>)}</div>}<p className="help-text">{kind==='secret'?'Le note dello schermo del DM sono sempre riservate al DM.':owner?'L’autore mantiene sempre l’accesso. Puoi escludere qualsiasi altro account, anche il DM.':'Solo l’autore può cambiare la visibilità. Chi può leggere può collaborare al contenuto.'}</p></div>
 {error&&<div role="alert" className="form-error">{error}</div>}<div className="editor-actions"><button type="button" className="btn ghost" disabled={busy} onClick={onClose}>Annulla</button><button type="submit" className="btn primary" disabled={busy||uploading||draft.body.length>60000}>{busy?'Salvataggio…':'Salva '+KINDS[kind].label.toLowerCase()}</button></div>
 </form></DialogContent></Dialog>;
}
