'use client';
import React,{useState,useRef,useEffect,useMemo} from 'react';
import {MapPin,Hand,Ruler,Users,Plus,Minus,Maximize,Undo2,Redo2,X,Route,Play,Pause,SkipBack,SkipForward,ChevronRight,ChevronLeft,Clock3,Feather,LocateFixed,Castle,Trees,Landmark,Skull,Search,Trash2,Save,ImagePlus,Eye,EyeOff,Layers,DoorOpen,MapPinned} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Slider} from '@/components/ui/slider';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {toast} from 'sonner';
import {IconButton,Choice,DateEditor} from './ui';
import {ImageField} from './image-fields';
import {dateLabel,timeLabel,placed,MAIN_MAP,type Entry,type State,type Point} from '@/lib/campaign';
import {MAP_RATIO,mapDistance,routeAnchors,sampleRoute,routeLength,pointAt,partialRoute,nearbyPlace} from '@/lib/routes';
type RouteDraft={id:string;entry:Entry;points:Point[];curve:boolean;selected:number;undo:Point[][];redo:Point[][]};
type Props={state:State;openEntry:(e:Entry)=>void;createEntry:(kind:any,data?:any)=>void;saveSettings:(changes:any)=>Promise<void>;saveEntry:(e:Entry)=>Promise<void>;history:boolean;setHistory:(v:boolean)=>void;pendingPosition:Entry|null;onPosition:(p:Point)=>void;openClock:()=>void;focusId:string|null;onRouteEditing?:(v:boolean)=>void};
const tokenIcons:Record<string,any>={pin:MapPin,castle:Castle,town:Landmark,trees:Trees,skull:Skull,clue:Search};
const clamp=(n:number)=>Math.max(0,Math.min(1,n));
export default function MapView({state,openEntry,createEntry,saveSettings,saveEntry,history,setHistory,pendingPosition,onPosition,openClock,focusId,onRouteEditing}:Props){
 const [mapId,setMapId]=useState('');
 const [tool,setTool]=useState('pan');const [zoom,setZoom]=useState(1);const [pan,setPan]=useState({x:0,y:0});const [size,setSize]=useState({w:900,h:600});const stage=useRef<HTMLDivElement>(null);const canvas=useRef<HTMLDivElement>(null);const drag=useRef<any>(null);const touches=useRef(new Map<number,Point>());const pinchRef=useRef<{distance:number;cx:number;cy:number;zoom:number;pan:Point}|null>(null);const [partyPreview,setPartyPreview]=useState<Point|null>(null);
 const [measure,setMeasure]=useState<Point[]>([]);const [terrain,setTerrain]=useState('1');const [calibrate,setCalibrate]=useState(false);const [knownMiles,setKnownMiles]=useState('1');const [hover,setHover]=useState('');const [showPins,setShowPins]=useState(true);
 const [selectedId,setSelectedId]=useState('');const [minute,setMinute]=useState<number|null>(null);const [playing,setPlaying]=useState(false);const [speed,setSpeed]=useState('1');const [route,setRoute]=useState<RouteDraft|null>(null);const [saving,setSaving]=useState(false);const [jump,setJump]=useState(false);const [jumpMinute,setJumpMinute]=useState(0);const [tokenOpen,setTokenOpen]=useState(false);const [tokenBusy,setTokenBusy]=useState(false);const [tokenImage,setTokenImage]=useState(state.settings.partyImage||'');
 const events=useMemo(()=>state.records.filter(r=>r.kind==='event').sort((a,b)=>a.data.minutes-b.data.minutes||a.id.localeCompare(b.id)),[state.records]);
 const routes=useMemo(()=>events.map((e,i)=>sampleRoute(routeAnchors(e,events[i-1]),e.data.curve===true)),[events]);
 const selected=events.find(e=>e.id===selectedId)||events[0];const index=selected?events.findIndex(e=>e.id===selected.id):0;const previous=events[index-1];const firstMinute=events[0]?.data.minutes??state.settings.minutes;const lastMinute=events.at(-1)?.data.minutes??firstMinute;const cursor=Math.max(firstMinute,Math.min(lastMinute,minute??firstMinute));
 let activeIndex=0;for(let i=0;i<events.length;i++){if(events[i].data.minutes<=cursor)activeIndex=i;}const nextEvent=events[activeIndex+1];const fraction=nextEvent?Math.max(0,Math.min(1,(cursor-events[activeIndex].data.minutes)/(nextEvent.data.minutes-events[activeIndex].data.minutes||1))):0;
 const party=history&&events.length?(nextEvent?pointAt(routes[activeIndex+1],fraction):{x:events[activeIndex].data.x,y:events[activeIndex].data.y}):state.settings.party;
 const nearby=nearbyPlace(state.settings.party,state.records,state.settings.mapWidthMiles,state.settings.locationRadiusMiles??.25);
 const routeSamples=useMemo(()=>route?sampleRoute(route.points,route.curve):[],[route?.points,route?.curve]);const selectedMiles=(route?routeLength(routeSamples):routeLength(routes[index]||[]))*state.settings.mapWidthMiles;
 useEffect(()=>{const el=stage.current;if(!el)return;const obs=new ResizeObserver(()=>setSize({w:el.clientWidth,h:el.clientHeight}));obs.observe(el);return()=>obs.disconnect();},[]);
 useEffect(()=>{if(history)setMapId('');if(!history){setPlaying(false);setRoute(null);}setTool('pan');},[history]);
 useEffect(()=>{setMeasure([]);setSelectedId('');setHover('');},[mapId]);
 useEffect(()=>{if(pendingPosition)setTool('position');else if(tool==='position')setTool('pan');},[pendingPosition]);
 useEffect(()=>{const el=stage.current;if(!el)return;const wheel=(e:WheelEvent)=>{e.preventDefault();const step=e.deltaMode===1?e.deltaY*16:e.deltaMode===2?e.deltaY*400:e.deltaY;zoomTo(Math.max(.25,Math.min(4,Math.exp(-step*(e.ctrlKey?.011:.0022)))),e.clientX,e.clientY);};el.addEventListener('wheel',wheel,{passive:false});return()=>el.removeEventListener('wheel',wheel);},[]);
 useEffect(()=>{onRouteEditing?.(!!route);if(!route)return;const guard=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',guard);return()=>{onRouteEditing?.(false);window.removeEventListener('beforeunload',guard);};},[!!route,onRouteEditing]);
 // La mappa principale e quella del sito e non e un contenuto salvato: le altre sono
 // voci di tipo «mappa», con immagine, proporzioni e scala proprie.
 const mapRecords=useMemo(()=>state.records.filter(r=>r.kind==='map'),[state.records]);
 const current=mapRecords.find(m=>m.id===mapId);
 const chain=useMemo(()=>{const out:Entry[]=[];let node=current;const guard=new Set<string>();while(node&&!guard.has(node.id)){guard.add(node.id);out.unshift(node);node=mapRecords.find(m=>m.id===node!.data.parent);}return out;},[current,mapRecords]);
 const sheet={id:current?current.id:'',title:current?current.title:MAIN_MAP.title,src:current?(current.data.image?'/api/media/'+current.data.image:''):MAIN_MAP.src,ratio:current?(current.data.ratio||MAIN_MAP.ratio):MAP_RATIO,
  widthMiles:current?(current.data.widthMiles||1):state.settings.mapWidthMiles,calibrated:current?current.data.calibrated===true:state.settings.mapCalibrated===true};
 const ratio=sheet.ratio;
 const children=mapRecords.filter(m=>(m.data.parent||'')===sheet.id&&m.id!==sheet.id);
 // Sulla mappa finiscono solo le voci che una posizione ce l'hanno davvero. Le altre
 // restano leggibili nel glossario e nell'elenco a lato, in attesa di essere collocate.
 const sheetPins=state.records.filter(r=>r.kind==='pin'&&(r.data.map||'')===sheet.id);
 const placedPins=sheetPins.filter(placed);const doors=children.filter(placed);
 const width=Math.min(size.w,size.h*ratio);const height=width/ratio;
 const view=useRef({zoom,pan,width,height});view.current={zoom,pan,width,height};
 function clampPan(p:Point,z:number,w=width,h=height):Point{const el=stage.current;if(!el)return p;const sw=el.clientWidth,sh=el.clientHeight;const mx=Math.max(0,(w*z-sw)/2)+sw*.32,my=Math.max(0,(h*z-sh)/2)+sh*.32;return{x:Math.max(-mx,Math.min(mx,p.x)),y:Math.max(-my,Math.min(my,p.y))};}
 function applyView(z:number,p:Point){const next=clampPan(p,z,view.current.width,view.current.height);view.current={...view.current,zoom:z,pan:next};setZoom(z);setPan(next);}
 function zoomTo(factor:number,clientX?:number,clientY?:number){const el=stage.current;if(!el)return;const r=el.getBoundingClientRect();const v=view.current;const next=Math.max(.65,Math.min(6,v.zoom*factor));if(Math.abs(next-v.zoom)<.0005)return;const fx=(clientX??r.left+r.width/2)-r.left-r.width/2,fy=(clientY??r.top+r.height/2)-r.top-r.height/2;const k=1-next/v.zoom;applyView(next,{x:v.pan.x+(fx-v.pan.x)*k,y:v.pan.y+(fy-v.pan.y)*k});}
 // Mettere a fuoco una voce aperta altrove (dal glossario, dalla ricerca, da un
 // collegamento). Se il segnalino sta su una mappa di dettaglio, prima si apre quella
 // e la centratura si completa al giro dopo, quando le proporzioni sono quelle giuste.
 const pendingFocus=useRef<string|null>(null);
 function centreOn(target:Entry){applyView(1.8,{x:(.5-target.data.x)*width*1.8,y:(.5-target.data.y)*height*1.8});setHover(target.id);}
 useEffect(()=>{if(!focusId)return;const target=state.records.find(r=>r.id===focusId);if(!target)return;
  if(target.kind==='event'){setSelectedId(target.id);setMinute(target.data.minutes);setPlaying(false);return;}
  if(target.kind==='map'){if(mapId!==target.id){setMapId(target.id);applyView(1,{x:0,y:0});}return;}
  if(target.kind!=='pin'||!placed(target))return;
  const home=target.data.map||'';
  if(home!==mapId){pendingFocus.current=target.id;setMapId(home);return;}
  centreOn(target);},[focusId]);
 useEffect(()=>{const id=pendingFocus.current;if(!id)return;pendingFocus.current=null;const target=state.records.find(r=>r.id===id);if(target)centreOn(target);},[mapId]);
 useEffect(()=>{if(!playing||events.length<2)return;let frame:number;let last=performance.now();let value=cursor;const tick=(now:number)=>{value+=(now-last)/1000*Number(speed)*60;last=now;if(value>=lastMinute){setMinute(lastMinute);setPlaying(false);return;}setMinute(value);frame=requestAnimationFrame(tick);};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame);},[playing,speed,events]);
 const pts=(arr:Point[])=>arr.map(p=>`${p.x*Math.round(ratio*1000)},${p.y*1000}`).join(' ');
 function position(e:{clientX:number;clientY:number}){const r=canvas.current!.getBoundingClientRect();return{x:clamp((e.clientX-r.left)/r.width),y:clamp((e.clientY-r.top)/r.height)};}
 function choose(t:string){setTool(t);if(t!=='measure')setMeasure([]);}
 function selectEvent(e:Entry){if(route)return;setSelectedId(e.id);setMinute(e.data.minutes);setPlaying(false);}
 function updatePoints(points:Point[],selectedIndex?:number){setRoute(r=>r?{...r,points,selected:selectedIndex??r.selected,undo:[...r.undo,r.points].slice(-30),redo:[]}:r);}
 function closestSegment(p:Point){if(!route)return 0;let closest=0,dist=Infinity;for(let i=0;i<route.points.length-1;i++){const a=route.points[i],b=route.points[i+1];const vx=b.x-a.x,vy=(b.y-a.y)/MAP_RATIO,wx=p.x-a.x,wy=(p.y-a.y)/MAP_RATIO;const t=clamp((vx*wx+vy*wy)/(vx*vx+vy*vy||1));const d=Math.hypot(wx-vx*t,wy-vy*t);if(d<dist){dist=d;closest=i;}}return closest;}
 function addNode(p:Point,after?:number){if(!route||route.points.length>=1000)return;const idx=(after??closestSegment(p))+1;updatePoints([...route.points.slice(0,idx),p,...route.points.slice(idx)],idx);}
 function deleteNode(){if(!route||route.selected<=0||route.selected>=route.points.length-1)return;updatePoints(route.points.filter((_,i)=>i!==route.selected),Math.max(0,route.selected-1));}
 // Due dita sullo schermo: la distanza fra loro pilota lo zoom, il punto medio lo spostamento.
 function pinchState(){const points=Array.from(touches.current.values());if(points.length<2)return null;const [a,b]=points;return{distance:Math.hypot(a.x-b.x,a.y-b.y),cx:(a.x+b.x)/2,cy:(a.y+b.y)/2};}
 function down(e:React.PointerEvent){if(e.button!==0||(e.target as HTMLElement).closest('button'))return;
  if(e.pointerType!=='mouse'){touches.current.set(e.pointerId,{x:e.clientX,y:e.clientY});const pinch=pinchState();if(pinch){drag.current=null;setPartyPreview(null);pinchRef.current={...pinch,zoom:view.current.zoom,pan:view.current.pan};stage.current?.setPointerCapture(e.pointerId);return;}}
  stage.current?.setPointerCapture(e.pointerId);const partyDrag=(e.target as Element).closest('[data-party]')&&state.user.role==='dm'&&!history;drag.current={kind:partyDrag?'party':'map',x:e.clientX,y:e.clientY,pan,moved:false};if(route&&tool==='draw'){const p=position(e);drag.current.kind='draw';drag.current.original=route.points;setRoute({...route,undo:[...route.undo,route.points].slice(-30),redo:[],points:[...route.points.slice(0,-1),p,route.points.at(-1)!]});}}
 function move(e:React.PointerEvent){
  if(e.pointerType!=='mouse'&&touches.current.has(e.pointerId)){
   touches.current.set(e.pointerId,{x:e.clientX,y:e.clientY});
   const pinch=pinchState(),start=pinchRef.current;
   if(pinch&&start){
    if(start.distance>0){const factor=pinch.distance/start.distance;const next=Math.max(.65,Math.min(6,start.zoom*factor));
     const el=stage.current;
     if(el){const r=el.getBoundingClientRect();const fx=pinch.cx-r.left-r.width/2,fy=pinch.cy-r.top-r.height/2;const k=1-next/start.zoom;
      applyView(next,{x:start.pan.x+(fx-start.pan.x)*k+(pinch.cx-start.cx),y:start.pan.y+(fy-start.pan.y)*k+(pinch.cy-start.cy)});}}
    return;
   }
  }
  const d=drag.current;if(!d)return;const dx=e.clientX-d.x,dy=e.clientY-d.y;if(Math.hypot(dx,dy)>3)d.moved=true;if(d.kind==='party'){setPartyPreview(position(e));return;}if(d.kind==='node'){const p=position(e);setRoute(r=>r?{...r,points:r.points.map((v,i)=>i===d.index?p:v)}:r);return;}if(d.kind==='draw'){const p=position(e);setRoute(r=>r&&r.points.length<1000&&mapDistance(r.points.at(-2)!,p)>.003?{...r,points:[...r.points.slice(0,-1),p,r.points.at(-1)!]}:r);return;}if(tool==='pan'){const p=clampPan({x:d.pan.x+dx,y:d.pan.y+dy},zoom);view.current={...view.current,pan:p};setPan(p);}}
 function up(e:React.PointerEvent){
  if(touches.current.delete(e.pointerId)&&touches.current.size<2)pinchRef.current=null;
  const d=drag.current;drag.current=null;if(!d)return;const p=position(e);if(d.kind==='party'){if(d.moved)void saveSettings({party:p}).catch(()=>{}).finally(()=>setPartyPreview(null));else setPartyPreview(null);return;}if(d.kind==='node'||d.kind==='draw'||d.moved)return;if(route&&tool==='nodes'){addNode(p);return;}if(tool==='pin')createEntry('pin',{...p,map:sheet.id});if(tool==='measure')setMeasure(m=>[...m,p]);if(tool==='party'&&state.user.role==='dm'&&!history)void saveSettings({party:p}).catch(()=>{});if(tool==='position')onPosition(p);}
 function editRoute(){if(!selected||!previous)return;setPlaying(false);setMinute(selected.data.minutes);setTool('nodes');setRoute({id:selected.id,entry:selected,points:routeAnchors(selected,previous),curve:selected.data.curve!==false&&selected.data.routeVersion===2,selected:0,undo:[],redo:[]});}
 async function persistRoute(){if(!route||!selected)return;setSaving(true);try{await saveEntry({...route.entry,data:{...route.entry.data,path:route.points.slice(1,-1),routeVersion:2,curve:route.curve}});setRoute(null);setTool('pan');}catch(e){toast.error((e as Error).message);}finally{setSaving(false);}}
 const measured=routeLength(measure);const miles=measured*sheet.widthMiles;const travel=miles/state.settings.speed*Number(terrain)*60;
 return <div className="map-workspace"><div className="map-header">
 <div className="map-header-title"><div className="eyebrow">{history?'CRONOLOGIA DELLA CAMPAGNA':sheet.id?'MAPPA COLLEGATA':'MAPPA DELLA CAMPAGNA'}</div><h1>{history?'Storia':sheet.title}</h1></div>
 <Tabs value={history?'history':'map'} onValueChange={v=>{if(!route)setHistory(v==='history');}}><TabsList className="atlas-tabs"><TabsTrigger disabled={!!route} value="map"><MapPin size={15}/>Mappa</TabsTrigger><TabsTrigger value="history"><Clock3 size={15}/>Storia</TabsTrigger></TabsList></Tabs>
 <span className="map-note">{history?`${events.length} eventi`:`${placedPins.length} luoghi${doors.length?' · '+doors.length+(doors.length===1?' mappa':' mappe'):''}${sheetPins.length>placedPins.length?' · '+(sheetPins.length-placedPins.length)+' da collocare':''}`}</span>
 <button className="text-button map-clock" onClick={openClock}><Clock3 size={15}/>{timeLabel(state.settings.minutes)}<span className="desktop-inline"> · {dateLabel(state.settings.minutes,state.settings.months)}</span></button>
 <button className="btn primary" disabled={!!route} onClick={()=>createEntry(history?'event':'pin',history?{...state.settings.party,minutes:state.settings.minutes}:{...(sheet.id?{x:.5,y:.5}:state.settings.party),map:sheet.id})}><Plus size={17}/>{history?'Nuovo evento':'Aggiungi luogo'}</button></div>
 {route&&<div className="route-toolbar"><div><strong>Modifica percorso</strong><span>{previous?.title} → {selected?.title}</span></div><div className="route-toolbar-actions"><IconButton label="Sposta la mappa" active={tool==='pan'} onClick={()=>setTool('pan')}><Hand size={17}/></IconButton><IconButton label="Aggiungi snodi" active={tool==='nodes'} onClick={()=>setTool('nodes')}><Plus size={17}/></IconButton><IconButton label="Traccia a mano libera" active={tool==='draw'} onClick={()=>setTool('draw')}><Feather size={17}/></IconButton><IconButton label="Annulla modifica" disabled={!route.undo.length} onClick={()=>setRoute(r=>r?{...r,points:r.undo.at(-1)!,undo:r.undo.slice(0,-1),redo:[...r.redo,r.points],selected:0}:r)}><Undo2 size={17}/></IconButton><IconButton label="Ripeti modifica" disabled={!route.redo.length} onClick={()=>setRoute(r=>r?{...r,points:r.redo.at(-1)!,redo:r.redo.slice(0,-1),undo:[...r.undo,r.points],selected:0}:r)}><Redo2 size={17}/></IconButton><button className="btn ghost" disabled={saving} onClick={()=>{setRoute(null);setTool('pan');}}>Annulla</button><button className="btn primary" disabled={saving} onClick={()=>void persistRoute()}><Save size={16}/>{saving?'Salvataggio…':'Salva percorso'}</button></div></div>}
 <div className="map-layout"><div className="map-main"><div ref={stage} className={'map-stage tool-'+tool} onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={e=>{touches.current.delete(e.pointerId);if(touches.current.size<2)pinchRef.current=null;drag.current=null;setPartyPreview(null);}}>
 <div ref={canvas} className="map-canvas" style={{width,height,transform:`translate(calc(-50% + ${pan.x}px),calc(-50% + ${pan.y}px)) scale(${zoom})`}}>{sheet.src?<img src={sheet.src} alt={'Mappa · '+sheet.title} draggable={false}/>:<div className="map-missing"><ImagePlus size={30}/><span>Questa mappa non ha ancora un’immagine.</span></div>}
 <svg className="map-overlay" viewBox={'0 0 '+Math.round(ratio*1000)+' 1000'} preserveAspectRatio="none" aria-hidden="true">{history&&!sheet.id&&events.map((e,i)=>{if(!i||route?.id===e.id)return null;const points=i<=activeIndex?routes[i]:i===activeIndex+1?partialRoute(routes[i],fraction):[];return points.length>1?<polyline key={e.id} points={pts(points)} fill="none" stroke="#c1516c" strokeWidth="4" strokeDasharray={e.data.path?.length?undefined:'9 6'} strokeLinecap="round" strokeLinejoin="round"/>:null;})}{history&&!sheet.id&&events.filter(e=>e.data.minutes<=cursor).map(e=><circle key={e.id} cx={e.data.x*Math.round(ratio*1000)} cy={e.data.y*1000} r="6" fill="#e1c4cc" stroke="#743041" strokeWidth="3"/>)}{route&&<><polyline points={pts(route.points)} fill="none" stroke="#cbd0dc" strokeOpacity=".45" strokeWidth="2" strokeDasharray="6 7"/><polyline points={pts(routeSamples)} fill="none" stroke="#e899ad" strokeWidth="5" strokeLinecap="round" strokeLinejoin="round"/></>}{measure.length>0&&<><polyline points={pts(measure)} fill="none" stroke="#e2d6e1" strokeWidth="4" strokeDasharray="7 5"/>{measure.map((p,i)=><circle key={i} cx={p.x*Math.round(ratio*1000)} cy={p.y*1000} r="6" fill="#6a3348" stroke="#ece4ec" strokeWidth="3"/>)}</>}</svg>
 {showPins&&!route&&placedPins.map(r=>{const Icon=tokenIcons[r.data.markerIcon]||(r.data.category==='natura'?Trees:Landmark);return <button key={r.id} className={'map-pin '+(hover===r.id?'hovered':'')} style={{left:r.data.x*100+'%',top:r.data.y*100+'%',transform:`translate(-50%,-100%) scale(${1/Math.sqrt(zoom)})`}} onPointerDown={e=>e.stopPropagation()} onClick={()=>openEntry(r)} onMouseEnter={()=>setHover(r.id)} onMouseLeave={()=>setHover('')} aria-label={'Apri '+r.title}><span>{r.data.markerImage?<img src={'/api/media/'+r.data.markerImage} alt=""/>:<Icon size={16}/>}</span><b>{r.title}</b></button>;})}
 {showPins&&!route&&doors.map(m=><button key={m.id} className="map-door" style={{left:(m.data.x??.5)*100+'%',top:(m.data.y??.5)*100+'%',transform:`translate(-50%,-100%) scale(${1/Math.sqrt(zoom)})`}} onPointerDown={e=>e.stopPropagation()} onClick={()=>{setMapId(m.id);applyView(1,{x:0,y:0});}} onDoubleClick={()=>openEntry(m)} aria-label={'Apri la mappa '+m.title} title={'Apri la mappa '+m.title}><span><DoorOpen size={16}/></span><b>{m.title}</b></button>)}
 {route&&route.points.map((p,i)=><button key={i} className={'route-node '+(i===route.selected?'selected':'')+(!i||i===route.points.length-1?' endpoint':'')} style={{left:p.x*100+'%',top:p.y*100+'%',transform:`translate(-50%,-50%) scale(${1/zoom})`}} aria-label={i===0?'Tappa di partenza':i===route.points.length-1?'Tappa di arrivo':'Snodo '+i} title={i===0?'Partenza':i===route.points.length-1?'Arrivo':'Trascina lo snodo '+i} onPointerDown={e=>{e.stopPropagation();setRoute(r=>r?{...r,selected:i}:r);if(i===0||i===route.points.length-1)return;stage.current?.setPointerCapture(e.pointerId);drag.current={kind:'node',index:i,x:e.clientX,y:e.clientY,moved:false};setRoute(r=>r?{...r,undo:[...r.undo,r.points].slice(-30),redo:[]}:r);}} onKeyDown={e=>{if(!i||i===route.points.length-1)return;const delta=e.shiftKey?.01:.001;const keys:Record<string,Point>={ArrowLeft:{x:-delta,y:0},ArrowRight:{x:delta,y:0},ArrowUp:{x:0,y:-delta},ArrowDown:{x:0,y:delta}};if(keys[e.key]){e.preventDefault();updatePoints(route.points.map((q,j)=>j===i?{x:clamp(q.x+keys[e.key].x),y:clamp(q.y+keys[e.key].y)}:q),i);}if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();updatePoints(route.points.filter((_,j)=>j!==i),0);}}}>{i===0?'A':i===route.points.length-1?'B':i}</button>)}
 {route&&route.points.slice(1).map((p,i)=>{const a=route.points[i];return <button key={'add'+i} className="route-add-node" style={{left:(a.x+p.x)*50+'%',top:(a.y+p.y)*50+'%',transform:`translate(-50%,-50%) scale(${1/zoom})`}} aria-label={'Aggiungi snodo nel tratto '+(i+1)} onPointerDown={e=>e.stopPropagation()} onClick={()=>addNode({x:(a.x+p.x)/2,y:(a.y+p.y)/2},i)}><Plus size={12}/></button>;})}
 {!route&&!sheet.id&&<div data-party className="party-marker" style={{left:(partyPreview||party).x*100+'%',top:(partyPreview||party).y*100+'%',transform:`translate(-50%,-50%) scale(${1/Math.sqrt(zoom)})`}} title={history?'Posizione nella cronologia':'Trascina per spostare il gruppo'}>{state.settings.partyImage?<img src={'/api/media/'+state.settings.partyImage} alt="Segnalino del gruppo"/>:<Users size={19}/>}<span>{history?'Gruppo · '+timeLabel(Math.floor(cursor)):'Il gruppo'}</span></div>}
 </div>
 {!history&&(mapRecords.length>0||state.user.role==='dm')&&<div className="map-layers" onPointerDown={e=>e.stopPropagation()}>
 <div className="map-layers-top"><Layers size={15}/><Choice label="Mappa aperta" value={sheet.id} onChange={v=>{setMapId(v);applyView(1,{x:0,y:0});}} options={[{value:'',label:MAIN_MAP.title+' · principale'},...mapRecords.map(m=>({value:m.id,label:m.title}))]}/>{state.user.role==='dm'&&<IconButton label="Aggiungi una mappa dentro questa" onClick={()=>createEntry('map',{parent:sheet.id,x:.5,y:.5,ratio:1.558,widthMiles:1})}><Plus size={16}/></IconButton>}</div>
 {!!chain.length&&<div className="map-crumbs"><button onClick={()=>{setMapId('');applyView(1,{x:0,y:0});}}>{MAIN_MAP.title}</button>{chain.map((m,i)=><React.Fragment key={m.id}><ChevronRight size={12}/>{i===chain.length-1?<span>{m.title}</span>:<button onClick={()=>{setMapId(m.id);applyView(1,{x:0,y:0});}}>{m.title}</button>}</React.Fragment>)}</div>}
 {current&&state.user.role==='dm'&&<button className="text-button" onClick={()=>openEntry(current)}><MapPinned size={14}/>Modifica questa mappa</button>}
 </div>}
 <div className="map-tools" onPointerDown={e=>e.stopPropagation()}>{!route&&<><IconButton label="Sposta la mappa" active={tool==='pan'} onClick={()=>choose('pan')}><Hand size={18}/></IconButton><IconButton label="Aggiungi luogo" active={tool==='pin'} onClick={()=>choose('pin')}><MapPin size={18}/></IconButton><IconButton label="Righello" active={tool==='measure'} onClick={()=>choose('measure')}><Ruler size={18}/></IconButton>{state.user.role==='dm'&&!history&&<IconButton label="Sposta il gruppo" active={tool==='party'} onClick={()=>choose('party')}><Users size={18}/></IconButton>}<IconButton label={showPins?'Nascondi i luoghi':'Mostra i luoghi'} active={showPins} onClick={()=>setShowPins(v=>!v)}>{showPins?<Eye size={18}/>:<EyeOff size={18}/>}</IconButton><div className="tool-divider"/></>}<IconButton label="Ingrandisci" onClick={()=>zoomTo(1.3)}><Plus size={18}/></IconButton><IconButton label="Riduci" onClick={()=>zoomTo(1/1.3)}><Minus size={18}/></IconButton><IconButton label="Mostra tutta la mappa" onClick={()=>applyView(1,{x:0,y:0})}><Maximize size={18}/></IconButton></div><div className="map-credit">{Math.round(zoom*100)}% · {sheet.calibrated?'SCALA CALIBRATA':'SCALA DA CALIBRARE'}</div>
 {['pin','party','position'].includes(tool)&&<div className="map-instruction" onPointerDown={e=>e.stopPropagation()}>{tool==='pin'?'Tocca la posizione del nuovo luogo':tool==='party'?'Tocca la nuova posizione del gruppo':'Tocca la posizione di questa voce'}<IconButton label="Annulla" onClick={()=>{choose('pan');if(pendingPosition)onPosition(pendingPosition.data as Point);}}><X size={16}/></IconButton></div>}
 {route&&<div className="route-map-hint">{tool==='nodes'?'Trascina gli snodi; usa + o tocca la mappa per aggiungerne altri.':tool==='draw'?'Trascina per aggiungere un tratto a mano libera.':'Trascina la mappa per spostarti.'}</div>}
 {tool==='measure'&&<div className="ruler-panel" onPointerDown={e=>e.stopPropagation()}><div className="row-between"><h3><Ruler size={17}/>Righello</h3><IconButton label="Chiudi" onClick={()=>choose('pan')}><X size={17}/></IconButton></div><p>{measure.length<2?'Seleziona almeno due punti.':'Distanza lungo i punti selezionati'}</p><div className="measure-values"><strong>{miles.toFixed(2)} <small>mi</small></strong><strong>{Math.floor(travel/60)}h {Math.round(travel%60)}m</strong></div><Choice label="Terreno" value={terrain} onChange={setTerrain} options={[{value:'1',label:'Terreno normale'},{value:'2',label:'Terreno difficile · tempo ×2'}]}/><div className="row-between"><span className="small muted">{state.settings.speed} mi/h</span><IconButton label="Rimuovi ultimo punto" onClick={()=>setMeasure(p=>p.slice(0,-1))}><Undo2 size={16}/></IconButton></div>{state.user.role==='dm'&&measure.length>=2&&<button className="text-button" onClick={()=>setCalibrate(true)}>Calibra distanza</button>}</div>}
 {!route&&tool==='pan'&&<div className="map-hint">{history?'Percorsi della cronologia · trascina per spostarti, rotella per lo zoom sul puntatore':'Trascina per spostarti · rotella per lo zoom sul puntatore'}</div>}
 </div>
 {history&&<div className="timeline-player timeline-v2"><div className="playback-controls"><IconButton label="Evento precedente" disabled={!events.length||!!route} onClick={()=>{const prev=[...events].reverse().find(e=>e.data.minutes<cursor)||events[0];selectEvent(prev);}}><SkipBack size={17}/></IconButton><button className="play-btn" disabled={events.length<2||!!route} aria-label={playing?'Pausa':'Riproduci'} onClick={()=>{if(cursor>=lastMinute)setMinute(firstMinute);setPlaying(p=>!p);}}>{playing?<Pause size={18}/>:<Play size={18}/>}</button><IconButton label="Evento successivo" disabled={!events.length||!!route} onClick={()=>selectEvent(events.find(e=>e.data.minutes>cursor)||events.at(-1)!)}><SkipForward size={17}/></IconButton></div><div className="timeline-track"><div className="row-between"><button className="text-button" disabled={!!route} onClick={()=>{setJumpMinute(Math.floor(cursor));setJump(true);}}>{dateLabel(Math.floor(cursor),state.settings.months)}</button><strong>{timeLabel(Math.floor(cursor))}</strong></div><Slider aria-label="Data e ora della cronologia" min={firstMinute} max={Math.max(firstMinute+1,lastMinute)} step={1} value={[cursor]} disabled={!events.length||!!route} onValueChange={([v])=>{setPlaying(false);setMinute(v);}}/><div className="row-between small muted"><span>{timeLabel(firstMinute)} · {events.length} eventi</span><Choice label="Velocità animazione" value={speed} onChange={setSpeed} options={[{value:'.25',label:'15 min / secondo'},{value:'1',label:'1 ora / secondo'},{value:'4',label:'4 ore / secondo'},{value:'12',label:'12 ore / secondo'}]}/></div></div></div>}
 </div>
 <aside className="map-aside"><div className="aside-title"><span className="eyebrow">{history?(route?'PERCORSO SELEZIONATO':'EVENTI'):'POSIZIONE E LUOGHI'}</span><Route size={16}/></div>{history?<>
 {route?<div className="route-details"><div className="route-metrics"><div><small>Distanza</small><strong>{selectedMiles.toFixed(2)} mi</strong></div><div><small>Marcia stimata</small><strong>{Math.floor(selectedMiles/state.settings.speed)}h {Math.round(selectedMiles/state.settings.speed%1*60)}m</strong></div></div><Choice label="Forma del percorso" value={route.curve?'curve':'line'} onChange={v=>setRoute(r=>r?{...r,curve:v==='curve'}:r)} options={[{value:'line',label:'Linea spezzata'},{value:'curve',label:'Curva attraverso gli snodi'}]}/><p className="help-text">La curva passa attraverso i punti di controllo. Aggiungi più snodi nei tornanti per seguire la strada.</p><div className="row-between"><span>{route.points.length-2} snodi intermedi</span><IconButton label="Elimina snodo selezionato" disabled={route.selected<=0||route.selected>=route.points.length-1} onClick={deleteNode}><Trash2 size={16}/></IconButton></div><div className="route-point-list">{route.points.map((p,i)=><button key={i} className={route.selected===i?'selected':''} onClick={()=>setRoute(r=>r?{...r,selected:i}:r)}><b>{i===0?'A':i===route.points.length-1?'B':i}</b><span>{i===0?'Partenza':i===route.points.length-1?'Arrivo':'Snodo '+i}</span><small>{(p.x*100).toFixed(1)} · {(p.y*100).toFixed(1)}</small></button>)}</div>{route.selected>0&&route.selected<route.points.length-1&&<div className="form-grid"><label className="field">X %<input type="number" min={0} max={100} step=".1" value={+(route.points[route.selected].x*100).toFixed(2)} onChange={e=>updatePoints(route.points.map((p,i)=>i===route.selected?{...p,x:clamp(+e.target.value/100)}:p))}/></label><label className="field">Y %<input type="number" min={0} max={100} step=".1" value={+(route.points[route.selected].y*100).toFixed(2)} onChange={e=>updatePoints(route.points.map((p,i)=>i===route.selected?{...p,y:clamp(+e.target.value/100)}:p))}/></label></div>}<button className="text-button" disabled={route.points.length<3} onClick={()=>updatePoints([route.points[0],route.points.at(-1)!],0)}>Rimuovi tutti gli snodi</button><p className="help-text">Per spostare A o B, modifica la posizione degli eventi. Le modifiche al percorso vengono applicate con “Salva percorso”.</p></div>:<>
 <div className="event-list">{events.length?events.map((ev,i)=><React.Fragment key={ev.id}>{(!i||Math.floor(ev.data.minutes/1440)!==Math.floor(events[i-1].data.minutes/1440))&&<div className="event-day-label">{dateLabel(ev.data.minutes,state.settings.months)}</div>}<button className={'event-row '+(selected?.id===ev.id?'selected':'')} onClick={()=>selectEvent(ev)}><span className="event-node"/><span><small>{timeLabel(ev.data.minutes)}</small><strong>{ev.title}</strong><span className="event-excerpt">{ev.body.replace(/\[\[[^\]]+\]\]/g,'').slice(0,80)}</span></span></button></React.Fragment>):<div className="aside-empty"><h3>Nessun evento registrato</h3><p>Aggiungi il primo evento con data, ora e posizione sulla mappa.</p><button className="btn outline" onClick={()=>createEntry('event',{...state.settings.party,minutes:state.settings.minutes})}><Plus size={16}/>Nuovo evento</button></div>}</div>
 {selected&&<div className="selected-event-panel"><h3>{selected.title}</h3><p>{dateLabel(selected.data.minutes,state.settings.months)} · {timeLabel(selected.data.minutes)}</p><button className="btn outline full" onClick={()=>openEntry(selected)}>Apri evento <ChevronRight size={16}/></button><button className="btn primary full" disabled={!previous} onClick={editRoute}><Route size={16}/>Modifica percorso</button>{previous?<div className="route-metrics"><div><small>Da {previous.title}</small><strong>{selectedMiles.toFixed(2)} mi</strong></div><div><small>Tempo in campagna</small><strong>{Math.floor((selected.data.minutes-previous.data.minutes)/60)}h {(selected.data.minutes-previous.data.minutes)%60}m</strong></div></div>:<p className="help-text">Il primo evento è il punto di partenza. Il percorso si modifica selezionando una tappa successiva.</p>}</div>}
 </>}
 </>:<>{sheet.id?<div className="current-location"><span className="location-badge"><Layers size={16}/>MAPPA</span><h2>{sheet.title}</h2><p>{sheet.calibrated?'Scala calibrata su questa mappa':'Scala di questa mappa da calibrare'}</p><button className="text-button" onClick={()=>{setMapId(chain.length>1?chain[chain.length-2].id:'');applyView(1,{x:0,y:0});}}><ChevronLeft size={15}/>Torna a {chain.length>1?chain[chain.length-2].title:MAIN_MAP.title}</button></div>:<div className="current-location"><span className="location-badge"><Users size={16}/>GRUPPO</span><h2>{nearby?.title||'In viaggio'}</h2><p>{nearby?'Entro '+(state.settings.locationRadiusMiles??.25)+' mi dal luogo':'Fuori dal raggio dei luoghi annotati'}</p><button className="text-button" onClick={()=>applyView(1.8,{x:(.5-state.settings.party.x)*width*1.8,y:(.5-state.settings.party.y)*height*1.8})}>Centra il gruppo <LocateFixed size={15}/></button>{state.user.role==='dm'&&<button className="text-button" onClick={()=>{setTokenImage(state.settings.partyImage||'');setTokenOpen(true);}}><ImagePlus size={15}/>Immagine segnalino</button>}</div>}<div className="aside-section"><div className="row-between"><span className="eyebrow">{sheet.id?sheet.title.toUpperCase():'LUOGHI'}</span><span className="count">{sheetPins.length}</span></div>{children.map(m=><button className="location-row" key={m.id} onClick={()=>{setMapId(m.id);applyView(1,{x:0,y:0});}}><span className="location-icon"><DoorOpen size={18}/></span><span><strong>{m.title}</strong><small>{placed(m)?'Mappa collegata':'Mappa collegata · da collocare'}</small></span><ChevronRight size={15}/></button>)}{[...placedPins,...sheetPins.filter(r=>!placed(r))].map(r=><button className={'location-row '+(placed(r)?'':'unplaced')} key={r.id} onClick={()=>openEntry(r)} onMouseEnter={()=>setHover(r.id)} onMouseLeave={()=>setHover('')}><span className="location-icon">{r.data.markerImage?<img src={'/api/media/'+r.data.markerImage} alt=""/>:placed(r)?<MapPin size={18}/>:<Search size={18}/>}</span><span><strong>{r.title}</strong><small>{placed(r)?(r.audience.includes('*')?'Condiviso':'Visibilità limitata'):'Posizione sconosciuta'}</small></span><ChevronRight size={15}/></button>)}</div>{!sheet.id&&<div className="aside-section recent"><button className="btn outline full" onClick={()=>createEntry('event',{...state.settings.party,minutes:state.settings.minutes})}><Clock3 size={16}/>Registra posizione</button></div>}</>}
 </aside></div>
 <Dialog open={calibrate} onOpenChange={setCalibrate}><DialogContent><DialogHeader><DialogTitle>Calibra la mappa</DialogTitle><DialogDescription>Indica la distanza reale del percorso misurato. La scala vale solo per la mappa aperta ora.</DialogDescription></DialogHeader><label className="field">Distanza in miglia<input type="number" min=".01" step=".25" value={knownMiles} onChange={e=>setKnownMiles(e.target.value)}/></label><button className="btn primary" disabled={!measured||+knownMiles<=0} onClick={async()=>{try{if(current)await saveEntry({...current,data:{...current.data,widthMiles:+knownMiles/measured,calibrated:true}});else await saveSettings({mapWidthMiles:+knownMiles/measured,mapCalibrated:true});setCalibrate(false);}catch{}}}>Salva scala</button></DialogContent></Dialog>
 <Dialog open={jump} onOpenChange={setJump}><DialogContent><DialogHeader><DialogTitle>Vai a data e ora</DialogTitle><DialogDescription>La posizione del gruppo viene interpolata lungo il percorso registrato.</DialogDescription></DialogHeader><DateEditor value={jumpMinute} onChange={setJumpMinute} settings={state.settings}/><button className="btn primary" onClick={()=>{setMinute(Math.max(firstMinute,Math.min(lastMinute,jumpMinute)));setPlaying(false);setJump(false);}}>Vai nella cronologia</button></DialogContent></Dialog>
 <Dialog open={tokenOpen} onOpenChange={setTokenOpen}><DialogContent><DialogHeader><DialogTitle>Segnalino del gruppo</DialogTitle><DialogDescription>L’immagine viene usata sulla mappa e nella cronologia.</DialogDescription></DialogHeader><ImageField label="Carica immagine" onBusy={setTokenBusy} value={tokenImage} onChange={setTokenImage}/><button className="btn primary" disabled={tokenBusy} onClick={async()=>{try{await saveSettings({partyImage:tokenImage});setTokenOpen(false);}catch{}}}>Salva segnalino</button></DialogContent></Dialog>
 </div>;
}
