'use client';
import React,{useEffect,useRef,useState} from 'react';
import {Link2,Unlink,Eye,Pencil} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Command,CommandInput,CommandList,CommandItem,CommandEmpty} from '@/components/ui/command';
import {KINDS,type Entry} from '@/lib/campaign';
const escape=(s:string)=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
function serialize(root:Node):string{let output='';root.childNodes.forEach((node,i)=>{if(node.nodeType===Node.TEXT_NODE){output+=node.textContent||'';return;}if(!(node instanceof HTMLElement))return;if(node.dataset.ref){output+='[['+node.dataset.ref+(node.dataset.label?'|'+node.dataset.label:'')+']]';return;}if(node.tagName==='BR'){output+='\n';return;}const block=['DIV','P','LI'].includes(node.tagName);if(block&&output&&!output.endsWith('\n'))output+='\n';output+=serialize(node);if(block&&i<root.childNodes.length-1&&!output.endsWith('\n'))output+='\n';});return output;}
export default function RichTextEditor({value,onChange,records,label='Testo'}:{value:string;onChange:(v:string)=>void;records:Entry[];label?:string}){
 const root=useRef<HTMLDivElement>(null);const selection=useRef<Range|null>(null);const emitted=useRef<string|null>(null);const [linkOpen,setLinkOpen]=useState(false);const [phrase,setPhrase]=useState('');const [selectedLink,setSelectedLink]=useState<HTMLElement|null>(null);
 useEffect(()=>{if(!root.current||value===emitted.current)return;const html=value.split(/(\[\[[^\]]+\]\])/g).map(part=>{if(!part.startsWith('[['))return escape(part).replaceAll('\n','<br>');const [id,...rest]=part.slice(2,-2).split('|');const record=records.find(r=>r.id===id);const text=record?(rest.join('|')||record.title):'Riferimento riservato';return '<span contenteditable="false" tabindex="0" class="editor-inline-link" data-ref="'+escape(id)+'"'+(record?' data-label="'+escape(rest.join('|'))+'"':'')+'>'+escape(text)+'</span>';}).join('');root.current.innerHTML=html;emitted.current=value;},[value,records]);
 function emit(){const next=serialize(root.current!);emitted.current=next;onChange(next);}
 function remember(){const s=window.getSelection();if(s?.rangeCount&&root.current?.contains(s.getRangeAt(0).commonAncestorContainer))selection.current=s.getRangeAt(0).cloneRange();}
 function insert(node:Node){const el=root.current!;let range=selection.current;if(!range||!el.contains(range.commonAncestorContainer)){range=document.createRange();range.selectNodeContents(el);range.collapse(false);}range.deleteContents();range.insertNode(node);range.setStartAfter(node);range.collapse(true);const s=window.getSelection();s?.removeAllRanges();s?.addRange(range);selection.current=range.cloneRange();el.focus();emit();}
 return <div className="rich-text-wrap"><div className="rich-text-toolbar"><label>{label}</label><button type="button" className="btn outline compact" onMouseDown={e=>{e.preventDefault();remember();}} onClick={()=>{setPhrase(selection.current?.toString()||'');setLinkOpen(true);}}><Link2 size={15}/>Inserisci collegamento</button>{selectedLink&&<button type="button" className="btn ghost compact" onClick={()=>{selectedLink.replaceWith(document.createTextNode(selectedLink.textContent||''));setSelectedLink(null);emit();}}><Unlink size={15}/>Rimuovi link</button>}</div><div ref={root} className="rich-text-input" contentEditable suppressContentEditableWarning role="textbox" aria-label={label} aria-multiline="true" data-placeholder="Scrivi il testo…" onInput={emit} onMouseUp={remember} onKeyUp={remember} onBlur={remember} onPaste={e=>{e.preventDefault();remember();insert(document.createTextNode(e.clipboardData.getData('text/plain')));}} onClick={e=>{const link=(e.target as HTMLElement).closest<HTMLElement>('[data-ref]');setSelectedLink(link);}} onKeyDown={e=>{if(e.key==='Enter'&&(e.target as HTMLElement).dataset.ref){e.preventDefault();setSelectedLink(e.target as HTMLElement);}}}/><p className="help-text">{value.length.toLocaleString('it-IT')} / 60.000 caratteri. Seleziona una parola o una frase e premi “Inserisci collegamento”. Per titoli ed elenchi puoi usare # e - a inizio riga.</p><Dialog open={linkOpen} onOpenChange={setLinkOpen}><DialogContent className="inline-link-dialog"><DialogHeader><DialogTitle>Inserisci un collegamento</DialogTitle><DialogDescription>Scegli la pagina da aprire quando si clicca sul testo.</DialogDescription></DialogHeader><label className="field">Testo del collegamento<input value={phrase} onChange={e=>setPhrase(e.target.value)} placeholder="Usa il titolo della pagina"/></label><Command><CommandInput placeholder="Cerca una pagina…"/><CommandList><CommandEmpty>Nessuna pagina disponibile.</CommandEmpty>{records.filter(r=>r.kind!=='folder').map(r=><CommandItem key={r.id} value={r.title+' '+r.id} onSelect={()=>{const span=document.createElement('span');span.contentEditable='false';span.tabIndex=0;span.className='editor-inline-link';span.dataset.ref=r.id;span.dataset.label=(phrase.trim()||r.title).replace(/[\[\]|]/g,'');span.textContent=span.dataset.label;setLinkOpen(false);requestAnimationFrame(()=>insert(span));}}><Link2 size={15}/><span>{r.title}</span><small>{KINDS[r.kind].label}</small></CommandItem>)}</CommandList></Command></DialogContent></Dialog></div>;
}
