'use client';
import React,{useState} from 'react';
import {Wheat,Users,Package,Settings2,Undo2,Minus,History,CalendarClock} from 'lucide-react';
import {Progress} from '@/components/ui/progress';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {supplyDays,dateLabel,timeLabel,type State,type Supplies} from '@/lib/campaign';
export default function SuppliesView({state,onMutate}:{state:State;onMutate:(data:any)=>Promise<void>}){const s=state.supplies;const days=supplyDays(s);const [edit,setEdit]=useState(false);const [draft,setDraft]=useState(s);const [version,setVersion]=useState(state.suppliesVersion);const [reason,setReason]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [consumeDays,setConsumeDays]=useState(1);const [confirm,setConfirm]=useState<'consume'|'undo'|null>(null);const [confirmVersion,setConfirmVersion]=useState(state.suppliesVersion);
 async function run(data:any){setBusy(true);setError('');try{await onMutate(data);setEdit(false);setConfirm(null);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const num=(n:number)=>n.toLocaleString('it-IT',{maximumFractionDigits:2});const shortDays=(n:number)=>num(n)+' giorni';
 return <div className="content-page supplies-page"><div className="page-heading"><div><div className="eyebrow">RISORSE CONDIVISE</div><h1>Provviste</h1></div><button className="btn primary" onClick={()=>{setDraft(s);setVersion(state.suppliesVersion);setReason('');setError('');setEdit(true);}}><Settings2 size={17}/>Aggiorna scorte</button></div>{(()=>{
  // Il consumo si registra a mano: qui ricordiamo quanti giorni di campagna sono
  // passati dall'ultimo movimento, con un pulsante che lo registra in un colpo solo.
  const last=s.history[0];if(!last)return null;
  const days=Math.floor((state.settings.minutes-last.at)/1440);
  if(days<1)return null;
  const needed=Math.round(days*s.partySize*s.foodPerPerson*100)/100;
  return <div className="supply-reminder"><div><CalendarClock size={19}/><div><strong>{days===1?'È passato un giorno':'Sono passati '+days+' giorni'} dall’ultimo movimento</strong><span>Servono {num(needed)} razioni per coprirli{needed>s.rations?' · le scorte non bastano':''}.</span></div></div><button className="btn outline" disabled={busy||needed>s.rations} onClick={()=>{setConsumeDays(days);setConfirm('consume');}}>Registra {days===1?'il giorno':'i '+days+' giorni'}</button></div>;
 })()}
 <div className="supply-summary"><div className="supply-total"><span className="eyebrow">AUTONOMIA COMPLESSIVA</span><strong>{num(days.days)} <small>giorni</small></strong><p>Calcolata sulle razioni e sul consumo del gruppo.</p><Progress value={Math.min(100,days.days/s.targetDays*100)} aria-label="Autonomia rispetto all’obiettivo"/><div className="row-between small muted"><span>{days.days<1?'Scorte inferiori a un giorno':Math.floor(days.days)+' giorni completi'}</span><span>Obiettivo: {s.targetDays} giorni</span></div></div><div className="supply-metric"><Wheat size={27}/><span>Cibo</span><strong>{num(s.rations)}</strong><small>razioni · {shortDays(days.food)}</small></div><div className="supply-metric"><Users size={27}/><span>Gruppo</span><strong>{s.partySize}</strong><small>persone da rifornire</small></div></div>
 <div className="supply-layout"><section className="surface-panel"><div className="row-between"><h2>Consumo giornaliero</h2><Package size={21}/></div><dl className="supply-facts"><div><dt>Cibo per persona</dt><dd>{num(s.foodPerPerson)} razioni</dd></div><div><dt>Cibo per il gruppo</dt><dd>{num(s.partySize*s.foodPerPerson)} razioni</dd></div></dl><div className="consume-controls"><label className="field">Giorni da consumare<input type="number" min=".01" max="365" step=".5" value={consumeDays} onChange={e=>setConsumeDays(+e.target.value)}/></label><button className="btn primary" disabled={busy||consumeDays<=0||consumeDays>days.days} onClick={()=>{setConfirmVersion(state.suppliesVersion);setConfirm('consume');}}><Minus size={17}/>Registra consumo</button></div><p className="help-text">Il consumo è manuale: avanzare l’orologio non modifica le scorte. Le quantità giornaliere sono personalizzabili.</p>{consumeDays>days.days&&<p className="low-supplies">Provviste insufficienti per {num(consumeDays)} giorni.</p>}</section><section className="surface-panel"><div className="row-between"><h2>Movimenti recenti</h2><History size={20}/></div>{s.history.length?<><div className="supply-history">{s.history.map(m=><div className="supply-history-row" key={m.id}><strong>{m.note}</strong><p>{dateLabel(m.at,state.settings.months)} · {timeLabel(m.at)} · {state.users.find(u=>u.id===m.by)?.name||'Utente'}</p><div><span>{m.rations>0?'+':''}{num(m.rations)} razioni</span></div></div>)}</div><button className="text-button" disabled={busy||s.history[0].reversed} onClick={()=>{setConfirmVersion(state.suppliesVersion);setConfirm('undo');}}><Undo2 size={16}/>Annulla ultimo movimento</button></>:<p className="panel-empty">Nessun movimento registrato.</p>}</section></div>{error&&!edit&&!confirm&&<p className="form-error" role="alert">{error}</p>}
 <Dialog open={edit} onOpenChange={v=>{if(!busy)setEdit(v);}}><DialogContent className="settings-dialog"><DialogHeader><DialogTitle>Scorte e consumo</DialogTitle><DialogDescription>Le modifiche sono condivise con tutto il gruppo.</DialogDescription></DialogHeader><form onSubmit={e=>{e.preventDefault();void run({action:'set',data:draft,note:reason||'Aggiornamento scorte',version});}}><div className="form-grid">{[{key:'rations',label:'Razioni disponibili',min:0},{key:'partySize',label:'Persone nel gruppo',min:1},{key:'targetDays',label:'Obiettivo di autonomia (giorni)',min:1},{key:'foodPerPerson',label:'Razioni per persona al giorno',min:.01}].map(f=><label className="field" key={f.key}>{f.label}<input type="number" required min={f.min} step={f.key==='partySize'?1:.01} value={draft[f.key as keyof Supplies] as number} onChange={e=>setDraft(d=>({...d,[f.key]:+e.target.value}))}/></label>)}</div><label className="field">Motivo del movimento<input value={reason} maxLength={200} onChange={e=>setReason(e.target.value)} placeholder="Es. rifornimento a Vallaki"/></label>{error&&<p className="form-error" role="alert">{error}</p>}<button className="btn primary" disabled={busy}>{busy?'Salvataggio…':'Salva scorte'}</button></form></DialogContent></Dialog>
 <AlertDialog open={!!confirm} onOpenChange={v=>{if(!busy&&!v)setConfirm(null);}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{confirm==='consume'?'Registrare il consumo?':'Annullare l’ultimo movimento?'}</AlertDialogTitle><AlertDialogDescription>{confirm==='consume'?`Verranno sottratte ${num(consumeDays*s.partySize*s.foodPerPerson)} razioni.`:'Verranno ripristinate le quantità precedenti. I consumi per persona e le altre impostazioni restano invariati.'}</AlertDialogDescription></AlertDialogHeader>{error&&<p className="form-error" role="alert">{error}</p>}<AlertDialogFooter><AlertDialogCancel disabled={busy}>Annulla</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={e=>{e.preventDefault();void run({action:confirm,days:consumeDays,version:confirmVersion});}}>Conferma</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </div>;
}
