'use client';
import React from 'react';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Tooltip, TooltipContent, TooltipTrigger } from '@/components/ui/tooltip';
import { Checkbox } from '@/components/ui/checkbox';
import { dateParts, toMinutes, type Settings } from '@/lib/campaign';
export function Choice({value,onChange,options,label,className='',disabled=false}:{value:string;onChange:(v:string)=>void;options:{value:string;label:string}[];label?:string;className?:string;disabled?:boolean}){return <Select value={value} onValueChange={onChange} disabled={disabled}><SelectTrigger aria-label={label} className={'choice '+className}><SelectValue/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select>;}
export function IconButton({label,children,active=false,...props}:React.ButtonHTMLAttributes<HTMLButtonElement>&{label:string;active?:boolean}){return <Tooltip><TooltipTrigger asChild><button {...props} type="button" aria-label={label} aria-pressed={active} className={'icon-btn '+(active?'active ':'')+(props.className||'')}>{children}</button></TooltipTrigger><TooltipContent>{label}</TooltipContent></Tooltip>;}
export function Check({checked,onChange,children,disabled=false}:{checked:boolean;onChange:(v:boolean)=>void;children:React.ReactNode;disabled?:boolean}){return <label className={'check-label '+(disabled?'muted':'')}><Checkbox checked={checked} disabled={disabled} onCheckedChange={v=>onChange(v===true)}/><span>{children}</span></label>;}
export function DateEditor({value,onChange,settings}:{value:number;onChange:(v:number)=>void;settings:Settings}){const p=dateParts(value);function set(k:string,v:number){const q={...p,[k]:v};onChange(Math.max(0,toMinutes(q.year,q.month,q.day,q.hour,q.minute)));}return <div className="date-editor"><label>Giorno<input type="number" min="1" max="28" value={p.day} onChange={e=>set('day',Math.max(1,Math.min(28,+e.target.value)))}/></label><label>Mese<Choice value={String(p.month)} onChange={v=>set('month',+v)} options={settings.months.map((m,i)=>({value:String(i),label:m}))}/></label><label>Anno BC<input type="number" min="735" max="1735" value={p.year} onChange={e=>set('year',Math.max(735,Math.min(1735,+e.target.value)))}/></label><label>Ora<input type="time" value={String(p.hour).padStart(2,'0')+':'+String(p.minute).padStart(2,'0')} onChange={e=>{const [hour,minute]=e.target.value.split(':').map(Number);if(Number.isFinite(hour)&&Number.isFinite(minute))onChange(toMinutes(p.year,p.month,p.day,hour,minute));}}/></label></div>;}
